### ISSUE TITLE
界面销毁路由没有自动取消

### ISSUE THREAD

**Issue by keepactive** [xiaojinzi123/Component#10]
我在我的界面中使用路由跳转,界面销毁并没有取消路由,回调还是回调了,这个是需要额外的配置还是咋的

**Comment by xiaojinzi123** [comment]
自动取消功能取决于你使用的时候使用的是 `Activity` 还是 `Fragment`,以下情况的不规范使用会发生没有自动取消

- 在 `Fragment` 里面使用 `Activity` 作为参数

```
Router.with(getActivity())...........
```

这种情况因为 Activity 没有销毁,所以你的 Fragment 销毁时不会自动取消的,你应该使用 
```
Router.with(fragment).....
```
除此之外的其他情况都不会发生无法自动取消,所以建议你使用的时候传递当前的 `Fragment` 作为参数
