### ISSUE TITLE
请问下大佬，类继承怎么处理啊

### ISSUE THREAD

**Issue by keternity** [xiaojinzi123/Component#101]
譬如有A和B两个Fragment ，A继承B，所有的服务注解是写在B里面的，当打开A页面的时候，就报错了。然后看了下编译文件，没有A的_inject文件，只有B的。这种情况怎么处理啊

**Comment by LinXueyuanStdio** [comment]
ctrl+C ctrl+V请

**Comment by keternity** [comment]
。。。我用的是Android Annotations框架，这不是没得玩了么。。。。

**Comment by LinXueyuanStdio** [comment]
啥意思

**Comment by keternity** [comment]
[Android Annotations](https://github.com/androidannotations/androidannotations)是个注解框架，编译后所有注解的文件都会自动继承原文件，生成一个新的文件。譬如写了一个 A.java 文件，编译的时候就会生成一个叫 A_.java 的文件

**Comment by LinXueyuanStdio** [comment]
恕我直言，这个注解框架，可维护性为 0
写起来可能很快，但后面维护的时候就坑了
跟butterknife一样，建议放弃

**Comment by keternity** [comment]
对的，老代码了，哎，难啊。现在在慢慢转换掉。那我就写个方法自己兼容下吧，谢啦，膜拜！！！

fun Any.componentInject(className: String? = null) {
    var injectClassName: String = (className ?: this.javaClass.name)
    whatIf(injectClassName.endsWith("_")) {
        injectClassName = injectClassName.substring(0, injectClassName.length - 1)
    }
    injectClassName += ComponentConstants.INJECT_SUFFIX
    try {
        val targetInjectClass = Class.forName(injectClassName)
        val inject = targetInjectClass.newInstance() as Inject<Any>
        inject.injectService(this)
        inject.injectAttrValue(this)
    } catch (ignore: Exception) {
        LogUtil.log("class '" + this.javaClass.name + "' inject fail")
    }
}

**Comment by xiaojinzi123** [comment]
![image](https://user-images.githubusercontent.com/12975743/131658228-6053d07f-595d-4f31-b134-11cbaf71dfc4.png)

注入的核心是最终通过对象 target.class 获取到名字. 
现在的情况是, 如果存在继承的情况. 注入的时候, 找的目标都是对象真实的实现的那个类. 也就是子类. 
那我这里注入的方法在提供一个重载. 允许你传入 Class targetClass.
貌似这个问题就可以得到解决.

**Comment by keternity** [comment]
是的^_^

**Comment by xiaojinzi123** [comment]
你用的是什么版本的. 我看下是否可以提供一下

**Comment by keternity** [comment]
最新版本的

**Comment by xiaojinzi123** [comment]
加群吧. 方便沟通

**Comment by keternity** [comment]
ok
