### ISSUE TITLE
scheme 如何设置

### ISSUE THREAD

**Issue by jiaoya** [xiaojinzi123/Component#102]
例如：https://github.com/xiaojinzi123/Component/issues  ”https://“替换成 ”abb://“

**Comment by xiaojinzi123** [comment]
你描述的具体点？在什么场景下你需要这个需求. 
你描述的不完整, 我没法给出解答

**Comment by jiaoya** [comment]
一个 完整的uri:   weixin://com.mm.yy/abc,   scheme=weixin host=com.mm.yy path=abc  我看到RouterAnno注解里并没有设置scheme的地方，所以问问 这个能不能设置，因为我这边每一个activity都对应一个标准的uri ，我如果用你这个框架改造，scheme怎么能设置呢

**Comment by xiaojinzi123** [comment]
https://github.com/xiaojinzi123/Component/blob/2.x/develop/changelog.md#v192
1.9.2 是支持的. 你用的什么版本

**Comment by jiaoya** [comment]
在哪里设置？没找到，文档上没有看到

**Comment by xiaojinzi123** [comment]
> 在哪里设置？没找到，文档上没有看到

就是 RouterAnno 这个注解就有 scheme 属性呀
