### ISSUE TITLE
query 的值

### ISSUE THREAD

**Issue by jiaoya** [xiaojinzi123/Component#104]
为什么 要设计成 通过ParameterSupport 获取 query 的值？而不是 通过解析query 直接 赋值到 bundle里，通过系统的 getIntent().getStringExtra(key)去获取，这样不是更加通用，理解更简单些吗

**Comment by xiaojinzi123** [comment]
哈哈哈, 兄弟, 你问这个问题至少你思考了. 挺好
原因是因为 query 的值在 Uri 中存着都是 String 类型的. 你没法事先知道是什么类型. 所以你也就没法存 bundle 的时候调用相对应的方法。

query 中的类型只有在获取的时候才能确定

比如你尝试获取 key 为 'name' 的 String值, 那么你通过 ParameterSupport 会尝试帮你获取. 首先获取到 key 为 'name' 的 String 类型的值. 发现你要的也是 String 类型, 那么就直接给你了

如果你尝试获取 key 为 'age' 的 Int 值, ParameterSupport 也会找到 key 为 'age' 的 String 类型的值 "25", 发现你要的是 Int, 那么此时 ParameterSupport 就会尝试帮你做类型转化. 然后你拿到了 25 这个 Int 值

总结一下, 你提的这个问题, 根本原因是因为 Query 的值在放进 Bundle 的时候, 是没法知道具体是什么类型的. 只能由目标界面获取的时候, 方能知道目标界面要的类型是什么, 然后进行相对应的转化. 希望能理解这点.

所以这就是 ParameterSupport 这个类的由来

**Comment by jiaoya** [comment]
ok，谢谢
