### ISSUE TITLE
关于ParameterSupport中的getXXX()方法的Nullable的注解

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#107]
举个例子：
`    @Nullable
    public static String getString(@NonNull Intent intent, @NonNull String key,
                                   @Nullable String defaultValue) {
        return getString(intent.getExtras(), key, defaultValue);
    }`
getString的已经有了defaultValue，然而还是Nullable，整个方法返回的也是Nullable，那么这个默认值感觉没有什么意义，也没有节省任何非空的判断

**Comment by xiaojinzi123** [comment]
对的 你说的没错, 感觉的出来你是写 Kotlin 的吧. 这个 Api 当初是基于 Java 设计的. 你说的这个在 Kotlin 中确实不好. 
在 2.x 的版本中其实已经慢慢的都迁移到 Kotlin 了. 但是因为注解驱动器那块的工作量巨大. 所以一直没有新的基于 Kotlin 的版本出来. 此问题是老问题, 还请体谅一下

**Comment by brandlee** [comment]
> 

了解，还是希望能够基于kotlin重构一版，现在已经从ARouter切换到了Component，使用上要比ARouter舒服太多，主要一点原因就是无法直接根据scheme来进行跳转真的是太难受了
