### ISSUE TITLE
java的路由静态方法转换成kotlin的顶级函数就无法跳转了，该怎么解决啊，代码如下

### ISSUE THREAD

**Issue by JeffChen001218** [xiaojinzi123/Component#109]
//java写法
@RouterAnno(
            host = ModuleConfig.ModuleSystemPages.NAME,
            path = ModuleConfig.ModuleSystemPages.SYSTEM_APP_DETAIL
    )
    public static Intent appDetail(@NonNull RouterRequest request) {
        Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        intent.setData(Uri.parse("package:" + request.getRawContext().getPackageName()));
        return intent;
    }

//kotlin写法
 @RouterAnno(
        host = ModuleConfig.ModuleSystemPages.NAME,
        path = ModuleConfig.ModuleSystemPages.SYSTEM_APP_DETAIL
    )
    fun appDetail(request: RouterRequest): Intent =
        Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS).apply {
            data = Uri.parse("package:" + request.rawContext?.packageName)
        }

**Comment by JeffChen001218** [comment]
写在Object里、加了@JvmStatic都无效，是因为框架获取注解方法时，只读java文件吗

**Comment by xiaojinzi123** [comment]
不用写在 Object 里面. 写在 .kt 文件中即可. 外面不要用 class 包的

**Comment by JeffChen001218** [comment]
试过了，也不行的，只有java里面才生效啊

**Comment by JeffChen001218** [comment]
还有一个问题，为什么通过如下代码，只能打开java的Activity，打不开kotlin的Activity啊，是不是我项目哪里配错了啊？，代码如下：
    fun goModule1ForResult(view: android.view.View) {
        Router
            .with(this)
            .host(ModuleConfig.Module1.NAME)
            .path(ModuleConfig.Module1.PAGE_MAIN)
//            .requestCode(REQUEST_FROM_APP)
            .forward({ request ->

            }, { errResult ->
                print(
                    "跳转module_1的main页面失败"
                )
            }, { successResult ->
                print(
                    "跳转module_1的main页面成功"
                )
            })
    }

**Comment by JeffChen001218** [comment]
解决了，是我配置错了

**Comment by xiaojinzi123** [comment]
真好, 我一忙没有及时回复, 你自己就解决了 哈哈哈. 那我关闭了这个 issue 了, 
有问题再打开
