### ISSUE TITLE
自动注入功能不支持 String[] ArrayList<String> 等

### ISSUE THREAD

**Issue by Xiaomingpapapa** [xiaojinzi123/Component#11]
我的界面上有数据是集合,但是用自动注入功能貌似不好使.好像就支持基本的几个数据类型

**Comment by xiaojinzi123** [comment]
> 我的界面上有数据是集合,但是用自动注入功能貌似不好使.好像就支持基本的几个数据类型

暂时先使用 ParameterSupport中的方法获取数据或者直接使用原生方法获取参数.你说的后续的版本会完善支持的.

**Comment by xiaojinzi123** [comment]
> 我的界面上有数据是集合,但是用自动注入功能貌似不好使.好像就支持基本的几个数据类型
最新的 1.7.0 版本支持了全部属性的注入功能,你可以在 `Activity`  写任何原本系统支持获取的属性了.
如下使用即可
```
@ParameterAnno("data")
string[] data;
```
