### ISSUE TITLE
Tag or commit '1.9.2' not found. Rechecking.

### ISSUE THREAD

**Issue by aheven** [xiaojinzi123/Component#110]
https://jitpack.io/com/github/xiaojinzi123/Component/component-impl-ktx/1.9.2/component-impl-ktx-1.9.2.pom
一直依赖不下来，jitpack文件库中也没找到啊...

**Comment by aheven** [comment]
implementation 'com.github.xiaojinzi123.Component:component-impl-ktx:v1.9.2-androidx-java8'
万万没想到后面还有个`androidx-java8`。

**Comment by xiaojinzi123** [comment]
哈哈哈 我看到的时候你自己解决了
