### ISSUE TITLE
啥时候能出v2.0.0正式版本呀

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#111]

**Comment by xiaojinzi123** [comment]
2.x 是用 Kotlin 写的. 没啥需求可以使用 1.9.x 的稳定版

**Comment by brandlee** [comment]
我就是使用的kotlin哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月12日(星期六) 中午12:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojinzi123/Component] 啥时候能出v2.0.0正式版本呀 (Issue #111)





 
2.x 是用 Kotlin 写的. 没啥需求可以使用 1.9.x 的稳定版
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaojinzi123** [comment]
你使用 Kotlin 和我用 Kotlin 写没有必然的关系呀. 你 Kotlin 也可以使用 1.9.x 的稳定版. 不影响呀.
我这边 2.x 迁移到 Kotlin 只是单纯的想全部使用 Kotlin 去编写而已

**Comment by xiaojinzi123** [comment]
全面升级到 Kotlin, 不支持 Java 的版本已经发布了
仓库是：https://github.com/xiaojinzi123/KComponent
这个 issue 就关闭了
