### ISSUE TITLE
多个路由跳转一个页面的情况

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#112]
有一个问题，麻烦请教一下：
多个路由都是跳转一个页面，根据路由的路径来跳转不同的tab，比如：“tab/market”就是在首页市场页面，“tab/message”就是在首页消息页面，这种情况能够在MainActivity类加上两个RouterAnno注解，然后在参数里面来区分么？

**Comment by xiaojinzi123** [comment]
第一种方式：
RouterAnno 支持正则. 你可以使用 tab/*
然后在 onCreate 中使用 ParameterSupport 获取 uri
拿到 Uri 对象你自己就可以匹配 market 或者 message 了

第二种方式：
RouterAnno 其实可以标记在静态方法上的. 
你可以在你的目标 Activity 创建两个静态方法, 然后分别使用 RouterAnno 标记, 在两个方法中, 你填入不同参数, 举例如下：
然后在界面中就可以使用 type 参数接了, 去到不同的 tab

```Java
public class TestAct extends AppCompatActivity{

    @RouterAnno(hostAndPath = “tab/market”)
    public static Intent test1(RouterRequest request) {
        Intent intent = new Intent(request.getRawContext(), TestAct.class);
        intent.putExtra("type", 1)
        return intent;
    }

    @RouterAnno(hostAndPath = “tab/message”)
    public static Intent test2(RouterRequest request) {
        Intent intent = new Intent(request.getRawContext(), TestAct.class);
        intent.putExtra("type", 2)
        return intent;
    }

}
```
