### ISSUE TITLE
关于混淆文件的问题

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#113]
这里面的类是不是有删除？这个提示找不到文件：
<img width="587" alt="image" src="https://user-images.githubusercontent.com/11416751/157607711-18308172-411c-494c-bae7-2eff3235fc19.png">

**Comment by xiaojinzi123** [comment]
是的, 提示的哪个是旧版本的
不过我自己也是如此配置的, 不会报错的吧 只不过会有下划线

**Comment by brandlee** [comment]
这个要不更新一下？这里发现已经没有这个类了 @xiaojinzi123

**Comment by xiaojinzi123** [comment]
行, 你那边没对应的类删了即可. 我文档更新下
