### ISSUE TITLE
defaultScheme能够对大小写不敏感么？

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#114]
在Compent初始化的时候，可以配置defaultScheme，有个问题请教一下：
项目最开始遵循驼峰命名法：类似"ZhiHu:"，但随着项目的演进，有的会支持scheme直接跳转App，这个时候需要全小写："zhihu"，这个时候defaultScheme支持大小写不敏感么？类似ignoreCase这种参数能够提供也行？

**Comment by xiaojinzi123** [comment]
其实这个问题你想的方向有点偏了. 
这个其实根本不需要我这边提供什么. 
你自己写个全局拦截器, 用来处理 scheme 即可. 把 N 种类型的 scheme 都转化成同一种. 
简单明了

**Comment by brandlee** [comment]
懂了，感谢感谢，我直接来通过拦截器处理吧

**Comment by xiaojinzi123** [comment]
记得用全局拦截器哦

**Comment by brandlee** [comment]
我是这样来处理的：
`@GlobalInterceptorAnno(priority = 10)

class SchemeInterceptor : RouterInterceptor {

    override fun intercept(chain: RouterInterceptor.Chain) {
        val originalRequest = chain.request()
        val isValidScheme = originalRequest.uri.scheme.equals(DEFAULT_SCHEME, ignoreCase = true)
        if (isValidScheme) {
            val newRequest = originalRequest.toBuilder().scheme(DEFAULT_SCHEME).build()
            chain.proceed(newRequest)
        } else {
            chain.callback().onError(Exception("Scheme is illegal"))
        }
    }
}`

**Comment by xiaojinzi123** [comment]
能完成需求就好. 没问题 老铁

**Comment by xiaojinzi123** [comment]
能完成需求就好. 没问题 老铁
