### ISSUE TITLE
页面级别Interceptor的优先级

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#115]
麻烦请教一下，对于页面，我们有`RouterAnno#interceptorNames`来添加页面级别的Interceptor，多个Interceptor是如何安排优先级的呢？

**Comment by xiaojinzi123** [comment]
RouterAnno 中有两种方式使用页面拦截器. 如果你只使用 interceptors 或者 interceptorNames 的一个. 那么本就是按照你配置的顺序执行的. 如果你  interceptors 和 interceptorNames 一起用了. 那么你需要使用 interceptorPriorities 和 interceptorNamePriorities 来分别配置他们对应的优先级的值. 
如果你对默认的行为不太清楚, 你还可以在编译 make 之后, 点击 RouterAnno 标记的 Activity 的引用, 找到 xxxRouterGenerated
的生成类, 看看生成的代码中的页面拦截器的优先级的值是多少. 比如图二中, 我的生成代码示例如下
![image](https://user-images.githubusercontent.com/12975743/159826153-97ae3f22-0ea1-4ae4-b7f5-1f81575cd128.png)
![image](https://user-images.githubusercontent.com/12975743/159826871-7768eca7-2f06-4c5f-bcac-d67702dd3ab2.png)

**Comment by brandlee** [comment]
可是我这里生成的代码，显示的全部都是0，我添加了三个Interceptor
<img width="763" alt="image" src="https://user-images.githubusercontent.com/11416751/159864988-2a4a2d50-1f7c-4ba2-9e0f-31a6cfdf8d14.png">

**Comment by xiaojinzi123** [comment]
你自己没运行过吗? 这种情况下根据排序不会打乱你原有的顺序. 这不是就符合你的预期了?

**Comment by brandlee** [comment]
我运行过，根据排序来决定问题没问题，符合我的预期。
我大概知道你的意思，在我这个情况下，是不是只有设置了`interceptorPriorities`才会改变这里的优先级？

**Comment by xiaojinzi123** [comment]
是呀
