### ISSUE TITLE
关于RouterFragment的一些困惑

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#116]
不得不说，Component真的非常好用，尤其是在需要越来越复杂的时候，现在有一点困惑，假设一个场景，一个Activity嵌套两个Fragment，通过路由我需要跳转到指定的Fragment，有2种实现方式：
1. 跳转url定义为`scheme://sample?tabIndex=1`，在Activity中获取`tabIndex`，然后切换到相应的Fragment；
2. 跳转url定义两个，分别为`scheme://XXX/sample/firstIndex`和`scheme://sample/secondIndex`，这个时候处理起来就会比较麻烦，我能想到的解决方式：通过正则表达式"^.*/sample/.*\$"，路由到相应的页面，然后通过Interceptor来进行转化。

想请教一下，这种情况有什么好的方式呢？

**Comment by xiaojinzi123** [comment]
Component 肯定是好用的呀. 我自己都用了好几年了. Arouter 说实话有这么好用吗, 但是懂得人太少. 

你这个需求是可以对一个 Activity 声明两个 RouterAnno 的. 这个具体去看：https://github.com/xiaojinzi123/Component/wiki/RouterAnno-%E6%B3%A8%E8%A7%A3

标记在静态方法上, 达到多个路由跳转一个界面. 

那你这个需求就可以是：
1. 写两个静态方法, 拿到 routerRequest 对象, 分别塞进去 tabIndex 参数. 一个为 0 另一个为 1
2. 然后在界面中 onCreate 中就可以获取 tabIndex 了. 根据 tabIndex 的值展示不同的 fragment

**Comment by brandlee** [comment]
看到了你说的这个方法，最终实现方式如下：
1. 添加两个静态方法，塞入tabIndex参数：
```
companion object {
        @RouterAnno(
            hostAndPath = “sample/firstIndex”,
            interceptors = [LoginInterceptor::class, XXXInterceptor::class]
        )
        fun createFirstIntent(request: RouterRequest): Intent {
            return Intent(request.rawContext, SampleActivity::class.java).apply {
                putExtra("tabIndex", 0)
            }
        }

        @RouterAnno(
            hostAndPath = “sample/secondIndex”,
            interceptors = [LoginInterceptor::class, XXXInterceptor::class]
        )
        fun createSecondIntent(request: RouterRequest): Intent {
            return Intent(request.rawContext, SampleActivity::class.java).apply {
                putExtra("tabIndex", 1)
            }
        }
    }
```

2. 在`SampleActivity`中获取参数：
`ParameterSupport.getInt(intent, “tabIndex”) ?: 0`

上述方式实现了我的问题，kotlin中也同样适用，感觉应该好好阅读一下Component的源码，现在用到的功能越来越多了，同时文档感觉可以更多的补全，有些问题可能只有使用的时候才能够发现问题。

比如Interceptor中，不仅仅是简单的LoginInterceptor，我们可能会需要在Interceptor中请求网络并等待返回结果后进行相应的操作，这个时候如果有示例就非常完美了。

再次感谢！

**Comment by brandlee** [comment]
还有一个问题，加入SampleActivity本来就存在，这个时候使用Router来唤起，是怎么来处理呢？

**Comment by xiaojinzi123** [comment]
没听懂你的需求.

**Comment by brandlee** [comment]
就是我要唤起的MainActivity一直在运行，我这个时候使用router调起，是什么结果

**Comment by xiaojinzi123** [comment]
你别把 Component 想的太复杂. Component 就是封装了路由跳转和服务发现. 
行为完全贴近原生. 所以你这个问题和 Component 没有关系. 
你对一个已经运行的 Activity 跳转, 这不是取决于你自己配置的启动模式嘛? 和 Component 一点关系没有. 
Component 只负责路由和服务发现调用. 明白了吗
