### ISSUE TITLE
afterXXXAction的优先级

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#117]
我看到afterXXXAction有很多方法：afterAction、afterErrorAction、afterEventAction、afterStartAction等，能在哪看到这些方法的优先级么？

**Comment by xiaojinzi123** [comment]
这个确实没有说明. 不过你好像很少自己测试. 其实这个自己测试下很容易就知道了. 
1. afterStartAction 是最先的. 
2. afterAction、afterErrorAction 是其中一个会执行. 
3. afterEventAction 在错误或者成功都会执行

**Comment by brandlee** [comment]
我会自己测试，但是是希望官方文档有说明。我测试的结果就是：afterAction、afterErrorAction 是其中一个会执行。但是我没有去将所有的Action全部进行测试，所以才会去官方文档中查找关于这一块的说明。
另外，我也差看过源码的注释，里面也没有说明其执行的优先级。我提这个issue的原因是想完善component的文档，便于后来的使用者，并不是很少自己来测试。

**Comment by xiaojinzi123** [comment]
我只是个个人开发者. 做不到特别细小的点都文档写的很清楚. 我并不是为了 Kpi 做的开源. 我也没那么多时间. 假如你自己维护一个比较庞大的项目 
我能做到的就是有 issue 的时候尽快的解决. 
你希望 afterStartAction 这类的 api 有详细的解释, 别人希望叫我整理个架构图, 又有人希望我做一个其他组件化框架的迁移文档, 还有人希望我能迁移到 Kotlin, 迁移到 ksp. 根本不会有满足的时刻. 我又不赚你钱, 我为了啥？
真的没有你想的那么简单的. 还望理解.

**Comment by brandlee** [comment]
了解，有空闲我希望能为这个开源库贡献一份力量

**Comment by brandlee** [comment]
很奇怪，我的afterAction在跳转成功之后没有被调用，跳转成功的是一个空的Activity，里面什么也没有实现。
<img width="824" alt="image" src="https://github.com/xiaojinzi123/Component/assets/11416751/067db669-200b-4afc-a668-aaa25526105d">
然后大概找到什么原因了，所有的Interceptor，都需要有chain的调用，不然的话after***Action不会调用。
