### ISSUE TITLE
请问下plugin支持增量吗？

### ISSUE THREAD

**Issue by Softtanck** [xiaojinzi123/Component#118]
版本:1.9.2

描述：
[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.xiaojinzi.component.ModuleAppProcessor (NON_INCREMENTAL), com.xiaojinzi.component.RouterProcessor (NON_INCREMENTAL), com.xiaojinzi.component.RouterDegradeProcessor (NON_INCREMENTAL), com.xiaojinzi.component.InterceptorProcessor (NON_INCREMENTAL), com.xiaojinzi.component.ServiceProcessor (NON_INCREMENTAL), com.xiaojinzi.component.FragmentProcessor (NON_INCREMENTAL), com.xiaojinzi.component.AutowireProcessor (NON_INCREMENTAL), com.xiaojinzi.component.RouterApiProcessor (NON_INCREMENTAL).

**Comment by xiaojinzi123** [comment]
不支持. 这个一直以来都不知道怎么去做. 我自己看到这信息也头疼. 
你懂的话可以帮忙下

**Comment by xiaojinzi123** [comment]
这个支持了已经
