### ISSUE TITLE
关于跳转到第三方SDK

### ISSUE THREAD

**Issue by brandlee** [xiaojinzi123/Component#119]
麻烦请教一下，现在Component已经支持注解静态方法了，比如跳转到系统指定页面：
`
* 系统 App 详情
*
* @param request
* @return
*/
@RouterAnno(
    host = ModuleConfig.System.NAME, 
    path = ModuleConfig.System.SYSTEM_APP_DETAIL
)
public static Intent appDetail(@NonNull RouterRequest request) {
    Activity act = request.getActivity();
    Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
    intent.setData(Uri.parse("package:" + request.getRawContext().getPackageName()));
    return intent;
}
`

如果我需要跳转到第三方SDK里面的方法，这个时候可以这么处理么？
`
* 系统 App 详情
*
* @param request
* @return
*/
@RouterAnno(
    host = ModuleConfig.System.NAME, 
    path = ModuleConfig.System.SYSTEM_APP_DETAIL
)
public static void appDetail(@NonNull RouterRequest request) {
    ThirdPartySDK.getInstance().openPage();
}
`

**Comment by xiaojinzi123** [comment]
不行的 你这个是动作. 不是路由

Component 路由是必须 intent 为基础的. 以前有过这个功能 被删了 和设计不符

**Comment by brandlee** [comment]
嗯嗯，我了解你设计的宗旨，是基于路由的，主要是现实的场景会有跳转到第三方的页面，但是只能通过SDK跳转，所以就想着能不能通过路由方法来实现。但是就像你说的，这是一个动作，不是路由。

**Comment by xiaojinzi123** [comment]
你这种通过 sdk 的. 你可以用协程包装一个 suspend 等一个结果. 
其他地方调用起来也很爽的呀.

**Comment by brandlee** [comment]
你说的应该是RouterApi for Coroutine吧？但是有一个问题，跳转第三方sdk的，其实也是一个scheme，调用起来就还是需要特殊来判断吧

**Comment by xiaojinzi123** [comment]
不是 ,我说的就是写一个简单正常的 suspend 的函数对 sdk 的跳转进行包装. 通常 sdk 的跳转都能回调结果的.

**Comment by brandlee** [comment]
服务器下发的直接就是一个scheme，就得对scheme特殊判断，如果是指定SDK的，然后再进行跳转了
