### ISSUE TITLE
单独调试模块，应该怎么做？

### ISSUE THREAD

**Issue by Bacchuc** [xiaojinzi123/Component#12]

**Comment by xiaojinzi123** [comment]
这个不支持,这个和组件化方案无关,你可以选择 [DDComponentForAndroid](https://github.com/luojilab/DDComponentForAndroid) 开源项目里面的 `Gradle` 调试插件.但是并不是 100% 兼容的,从 `DDComponentForAndroid` 项目中的 `issue` 就可以看出来.<br/>
另外你也可以新建一个 `Module` 去包含你想要单独运行的 `Module` 达到目的.这种方式是最保险且接近原生的.缺点就是会造成 `Module` 比较多.这个看你个人怎么选择了.<br/>
反正最终的目的是可以单独调试,这其实和组件化方案并没有多大的关系,你可以再看看其他的单独运行的方式,选择一种适合的就可以了,也不是很重要的问题

**Comment by Bacchuc** [comment]
好滴，谢谢

**Comment by xiaojinzi123** [comment]
这里我又总结了一下单独运行方面的内容,有兴趣的可以看下.
[单独运行总结](https://github.com/xiaojinzi123/Component/wiki/%E4%B8%9A%E5%8A%A1%E7%BB%84%E4%BB%B6%E5%8D%95%E7%8B%AC%E8%BF%90%E8%A1%8C)
