### ISSUE TITLE
依赖高概率的找不到

### ISSUE THREAD

**Issue by zhaoxiaowen-sven** [xiaojinzi123/Component#120]
这2个依赖高概率查找不到：
Could not get resource 'https://repo.maven.apache.org/maven2/com/github/xiaojinzi123/Component/component-compiler/1.8.8/component-compiler-1.8.8.pom'.

 Could not GET 'https://jitpack.io/com/github/xiaojinzi123/Component/component-compiler/1.8.8/component-compiler-1.8.8.pom'.
以第一个为例，在这个地址下，没有 xiaojinzi123
https://repo.maven.apache.org/maven2/com/github/

**Comment by xiaojinzi123** [comment]
1. 第一, 你使用的版本太老了. 
2. 第二, 我从来没有在 jitpack.io 之外的平台发布过. 所以请认准 jitpack.io 平台.

另外, 我看了一下 jitpack.io 上的 1.8.8 还在. 
https://jitpack.io/#xiaojinzi123/Component/v1.8.8

**Comment by zhaoxiaowen-sven** [comment]
再补充下信息
      > Could not resolve com.github.xiaojinzi123.Component:component-compiler:1.8.8.
         > Could not get resource 'https://jitpack.io/com/github/xiaojinzi123/Component/component-compiler/1.8.8/component-compiler-1.8.8.pom'.
            > Could not GET 'https://jitpack.io/com/github/xiaojinzi123/Component/component-compiler/1.8.8/component-compiler-1.8.8.pom'.
               > Connection reset
// 依赖
kapt "com.github.xiaojinzi123.Component:component-compiler:1.8.8"

**Comment by zhaoxiaowen-sven** [comment]
这个路径 浏览器也无法打开
https://jitpack.io/com/github/xiaojinzi123/Component/component-compiler

**Comment by zhaoxiaowen-sven** [comment]
sorry ， 公司IT加了代理 墙了
