### ISSUE TITLE
Failed to resolve: com.github.xiaojinzi123.Component:component-impl:1.9.2-androidx-java8

### ISSUE THREAD

**Issue by 199310lxw** [xiaojinzi123/Component#121]
编译提示：Failed to resolve: com.github.xiaojinzi123.Component:component-impl:1.9.2-androidx-java8  为啥

**Comment by xiaojinzi123** [comment]
jitpack.io 仓库添加了吗？
如果添加了那就考虑下你们自己公司是否对这个域名禁止了

**Comment by 199310lxw** [comment]
> jitpack.io 仓库添加了吗？ 如果添加了那就考虑下你们自己公司是否对这个域名禁止了

添加了，公司之前项目component可以用，现在项目添加这个报这个问题

**Comment by xiaojinzi123** [comment]
setting 文件中添加仓库地址就行了
