### ISSUE TITLE
咨询一下doOpenUri的问题

### ISSUE THREAD

**Issue by goIntoAction** [xiaojinzi123/Component#122]
首先感谢作者开源此库，造福其他开发。
没仔细看源码，现在碰到一个问题
在FirstActivity启动SecondActivity，马上finish FirstActivity，代码如下

Router.with(this).hostAndPath("main/second").forward()
finish()

当走到doOpenUri时，FirstActivity已经被destroy，这里为什么都在主线程，destroy却比界面跳转还早，是Component库中途做了什么异步操作导致的吗？我看到有调用post，能解释一下为什么吗？能否让使用者来决定是否用post？不然会出现程序没按照使用者初衷来执行的情况

**Comment by xiaojinzi123** [comment]
首先你没有仔细看跳转的文档. 文档中明确说了这种使用情况是一种错误的使用方式. 
另外解释下原因：
因为路由跳转的设计, 本该是异步线程的, 但是考虑其实 Android 绝大多数的场景的代码都是主线程调用的. 
只有真正需要异步的 IO、数据库 等需要子线程. 所以我设计的路由跳转是采用不断的 post 到主线程实现的. 
所以你会发现, 在拦截器中, 打印的线程是主线程. 这就是原因. 
另外注意：不断的 post 到主线程是实现整体路由跳转的假 "异步", 所以在拦截器中不要做卡住线程的操作. 如果需要 IO, 可以自行开线程或者使用 RxJava 或者协程去实现, 只要最后记得调用 chain.process 方法让拦截器继续即可, 或者调用 chain.callback().onError() 进行错误返回.

所以这就解释了为什么下面的代码是 finish() 先执行的
```Java
Router.with(this).hostAndPath("main/second").forward()
finish()
```

所以请在回调后调用. 
我习惯用 Kotlin, 我一般如此使用 
```
Router
.with(this)
.hostAndPath("main/second")
.forward {
      finish()
}
```

还有为啥 arouter 没有这问题, 因为它踏马的默认推荐的就是不带 context 的跳转, 使用 application 的 context, 所以压根不会有这问题. 
在我的框架中, 我是极力不推荐使用 application 的, 有 activity 的一定要带 activity 的.
因为 Component 的拦截器很强大, 特别是页面拦截器, 可以帮助目标页面进行预处理一些事情. 甚至可以在拦截器中做弹框、loading 等操作. 具体可以看 Demo
