### ISSUE TITLE
请问Component与ActivityResultContract如何配合使用？

### ISSUE THREAD

**Issue by goIntoAction** [xiaojinzi123/Component#123]
ActivityResultContract有两个抽象方法要实现

```
createIntent(context: Context, unit: Unit)
parseResult(resultCode: Int, intent: Intent?)
```

我尝试在createIntent返回ProxyIntent，发现parseResult会马上被调用
如果不行我就直接用forwardForResult吧

**Comment by xiaojinzi123** [comment]
问问题注意说明场景 你这么描述 我不太清楚你想要干啥。。

**Comment by goIntoAction** [comment]
场景就是需要拿到其他activity的result，之前用arouter和ActivityResultContract，利用arouter拿到真实的Intent返回给ActivityResultContract。想问下Component能拿到真正的Intent吗

**Comment by xiaojinzi123** [comment]
在我这里根本不需要用 ActivityResultContract 呀.
 Component 本身就支持拿 ActivityResult. 使用支持多种方式, 回调、RxJava、协程 等等
你没看文档吗？
