### ISSUE TITLE
forwardForResult再activity异常destroy后再次调用无效

### ISSUE THREAD

**Issue by wjzabc** [xiaojinzi123/Component#127]
ActivityA 调用        
Router.with(this)
                .host(ModuleConfig.File.HOST_FILE)
                .path(path).putString(ModuleConfig.Scanner.TYPE, type)
                .requestCode(FileConstant.REQUEST_CODE_DETAIL_ACTIVITY)
                .forwardForResult
跳转到ActivityB, B在前台处理大量图片，导致低内存，A被系统destroy，然后back返回到A , 此时A调用以上代码跳转到B失效。

**Comment by xiaojinzi123** [comment]
跳转失败吧 应该是 原因应该是使用了同一个 requestCode 的缘故

第一：你requestCode 不需要自己声明, 叫 框架自己创建一个即可, requestCodeRandom 方法即可
第二：我这边会做一个优化, 假设 requestCode 对应的 Activity 已经结束了, 我会对内置的 requestCode 池子进行移除

**Comment by xiaojinzi123** [comment]
不对 A 销毁的时候, 会取消路由的, 不是我刚刚说的问题。。 你最好查看具体的跳转失败的信息
