### ISSUE TITLE
模块和工程大了之后，编译速度特别慢， 是否支持模块化编译aar吗？比如 RocketX

### ISSUE THREAD

**Issue by mackzheng** [xiaojinzi123/Component#133]

**Comment by xiaojinzi123** [comment]
1. 如果全是 Kotlin, 可以迁移到 [KComponent](https://github.com/xiaojinzi123/KComponent)
ksp 会比 apt 快一些. 
2. 然后你还可以考虑业务模块打包成 aar 形式依赖. 也是没问题的. 不过开发麻烦很多, 我不太建议的
3. 至于你说的 RocketX, 换句话说就是能否支持更快的启动, 我这边没有相关的经验的.. 实力不太行. 不知道这么去做

**Comment by zhaoxiaowen-sven** [comment]
+1 Rocketx 缓存编译的aar ，我尝试了demo 工程 编译不过 


贴一个rockex 的链接 https://github.com/trycatchx/RocketX

**Comment by xiaojinzi123** [comment]
我有个问题, 就是如果注释注解驱动器 和 关闭 Component 的 Gradle 插件之后. 重新构建项目的时间和使用了注解驱动器以及Gradle 插件的时间对比你们能给一个吗？
因为我自己是已经用 KComponent 很久了, 这个数据我没法自己得到, 你们能提供下吗？
1. 啥都注释: xxx 秒
2. 使用注解驱动器: xxx 秒
3. 使用注解驱动器和 gradle 插件：xxx 秒

**Comment by mackzheng** [comment]
主要是混合工程，java ，kotlin  jni  都有。

**Comment by mackzheng** [comment]
主要是混合工程，java ，kotlin， jni 都有。
也在改造， 还在持续，ksp确实能将 kapt 的耗时降低些，当底层模块 修改，不涉及上层引用模块修改  还是比较耗时。
