### ISSUE TITLE
module能否独立运行测试？

### ISSUE THREAD

**Issue by f262866551** [xiaojinzi123/Component#134]
假如我项目多个人协同开发，每个人负责不同的module，module能否独立允许通讯啊

**Comment by xiaojinzi123** [comment]
这个问题我在很多地方甚至博客中多次解释了
[参看链接](https://github.com/xiaojinzi123/Component/wiki/%E4%B8%9A%E5%8A%A1%E7%BB%84%E4%BB%B6%E5%8D%95%E7%8B%AC%E8%BF%90%E8%A1%8C)

**Comment by f262866551** [comment]
> 

明白了，谢谢
