### ISSUE TITLE
使用com.xiaojinzi.component.plugin 编译报错

### ISSUE THREAD

**Issue by lotosbin** [xiaojinzi123/Component#135]
gradle wapper 7.6.2
android gradle plugin 7.4.2
compileSdk 33

报错如下：
Multiple build operations failed.
    Could not resolve all files for configuration ':app:androidApis'.
    Could not resolve all files for configuration ':emp-service:androidApis'.
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: /Users/liubinbin/Library/Android/sdk/platforms/android-33/android.jar.

**Comment by xiaojinzi123** [comment]
kotlin 版本是不是升级 1.8 + 了

**Comment by lotosbin** [comment]
kotlin 1.6.21

**Comment by lotosbin** [comment]
buildscript {
    dependencies {
        classpath "com.android.tools.build:gradle:${libs.versions.androidGradlePlugin.get()}"
    }
}
buildscript 加上classpath，可以正常编译了，

**Comment by xiaojinzi123** [comment]
插件依赖 agp 的

**Comment by lotosbin** [comment]
agp是使用plugins 引入的

**Comment by xiaojinzi123** [comment]
> agp是使用plugins 引入的

plugins 那边和下面这个不通的
buildscript {
dependencies {
}
}

**Comment by lotosbin** [comment]
component-plugin应该可以依赖plugins中的agp，而不是buildscript 中classpath的。但是相关文档一时找不到了。
这个报错很难想到是 classpath中缺少依赖，可以临时检查classpath中是否有agp，抛出更明确的异常。
