### ISSUE TITLE
1.9.4版本app模块依赖1.9.3版本编译的aar时，路由、服务获取都是null

### ISSUE THREAD

**Issue by lotosbin** [xiaojinzi123/Component#139]

**Comment by xiaojinzi123** [comment]
兄弟, 最近比较忙, 先挂着 后面我有时间再来解决

**Comment by lotosbin** [comment]
https://github.com/xiaojinzi123/Component/blob/2b6c3d4de1f1cc18439e733dca38d01ed07dc692/ComponentPlugin/src/main/java/com/xiaojinzi/component/plugin/ComponentPlugin1.kt#L147C50-L147C63

ASMUtilClassGen.getBytes 的moduleNameMap 看代码value应该是 simpleName
