### ISSUE TITLE
找不到模块，发现找找的路径不对

### ISSUE THREAD

**Issue by jiaoya** [xiaojinzi123/Component#142]
模块路由，生成代码的路径是：com.xiaojinzi.component.impl.Module_mainRouterGenerated 
但是你通过反射找的路径是：com.xiaojinzi.component.impl.application.Module_mainModuleAppGenerated
这个带application的是找不到的，这是什么原因，是模块gradle里没有配置好吗？

**Comment by zjxckangkang** [comment]
我也碰到类似问题了，用的1.9.4版本，自动注入报错，所以用的反射方式，报错和你类似。
最后解决方法是增加一个AppModuleApplication，使用ModuleAppAnno，这个类在demo中是有的。

`package com.xiaojinzi.componentdemo;

import android.app.Application;
import androidx.annotation.NonNull;
import android.util.Log;

import com.xiaojinzi.component.anno.ModuleAppAnno;
import com.xiaojinzi.component.application.IApplicationLifecycle;
import com.xiaojinzi.component.application.IModuleNotifyChanged;
import com.xiaojinzi.component.impl.Router;
import com.xiaojinzi.component.impl.RouterErrorResult;
import com.xiaojinzi.component.impl.RouterListener;
import com.xiaojinzi.component.impl.RouterRequest;
import com.xiaojinzi.component.impl.RouterResult;
import com.xiaojinzi.component.support.LogUtil;
import com.xiaojinzi.component.support.Utils;

@ModuleAppAnno()
public class AppModuleApplication implements IApplicationLifecycle, IModuleNotifyChanged {

    private final String TAG = "自定义实现的路由监听";

    private RouterListener listener = new RouterListener() {

        @Override
        public void onSuccess(@NonNull RouterResult successResult) throws Exception {
            RouterRequest originalRequest = successResult.getOriginalRequest();
            Log.e(TAG, "路由成功：" + originalRequest.uri.toString() + ",requestCode is " + (originalRequest.requestCode == null ? "null" : originalRequest.requestCode));
        }

        @Override
        public void onError(RouterErrorResult errorResult) throws Exception {
            RouterRequest originalRequest = errorResult.getOriginalRequest();
            if (originalRequest == null) {
                Log.e(TAG, "路由失败：errorMsg = " + Utils.getRealMessage(errorResult.getError()));
            } else {
                Log.e(TAG, "路由失败：" + originalRequest.uri.toString()
                        + " ,errorMsg = " + Utils.getRealMessage(errorResult.getError())
                        + "\nrequestCode is " + (originalRequest.requestCode == null ? "null" : originalRequest.requestCode)
                );
            }
        }

        @Override
        public void onCancel(@NonNull RouterRequest originalRequest) throws Exception {
            Log.e(TAG, "路由被取消：" + originalRequest.uri.toString() + ",requestCode is " + (originalRequest.requestCode == null ? "null" : originalRequest.requestCode));
        }
    };

    @Override
    public void onCreate(@NonNull Application app) {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            // ignore
        }
        Router.addRouterListener(listener);
    }

    @Override
    public void onDestroy() {
        Router.removeRouterListener(listener);
    }

    @Override
    public void onModuleChanged(@NonNull Application app) {
        LogUtil.loge("'模块发生变化啦");
    }

}
`

**Comment by zjxckangkang** [comment]
我也碰到类似问题了，用的1.9.4版本，自动注入报错，所以用的反射方式，报错和你类似。
最后解决方法是增加一个AppModuleApplication，使用注解ModuleAppAnno，这个类在demo中是有的。

**Comment by xiaojinzi123** [comment]
扫码进群 我看看问题

**Comment by xiaojinzi123** [comment]
![QQ_1720776817033](https://github.com/user-attachments/assets/8e0861eb-fafb-4b89-a066-3221b0e017cc)
有个警告, 不知道为啥会出现这个警告.

**Comment by xiaojinzi123** [comment]
这个问题不是框架的原因. 是 kapt 或者注解驱动器升级. 导致框架内初始化生成的那个默认的 模块级别的 生命周期类失败了
所以我重新发了一个版本 v1.9.6, 直接取消了模块初始化的时候生成那个默认的生命周期类
所以这就要求你们每一个模块都必须配置上 @ModuleAppAnno 标记的那个  模块级别的 生命周期类
如果注解标记的所有地方都已经是 Kotlin 了, 强烈建议直接使用 [KComponent](https://github.com/xiaojinzi123/KComponent)
没有这个问题, 还更好用
