### ISSUE TITLE
跟Hilt结合使用BaseProcessor会抛编译异常

### ISSUE THREAD

**Issue by xuexixuexijpg** [xiaojinzi123/Component#148]
使用Hilt2.46版本之后就会抛出编译异常，2.45版本正常，不知道Hilt做了啥导致导致了问题，如下：
![image](https://github.com/user-attachments/assets/5a222330-e487-4af9-8122-cd9b31f608ee)

**Comment by xuexixuexijpg** [comment]
拉源码看了下，为啥会少参数啊，这是Hilt的Bug吗？
![image](https://github.com/user-attachments/assets/b51cb84e-827f-402a-8e4b-92e38517cbec)

**Comment by xiaojinzi123** [comment]
> 拉源码看了下，为啥会少参数啊，这是Hilt的Bug吗？ ![image](https://private-user-images.githubusercontent.com/57759182/388323909-b51cb84e-827f-402a-8e4b-92e38517cbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTU4ODYsIm5iZiI6MTczMjE1NTU4NiwicGF0aCI6Ii81Nzc1OTE4Mi8zODgzMjM5MDktYjUxY2I4NGUtODI3Zi00MDJhLThlNGItOTJlMzg1MTdjYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MmZhNGZlYzZkY2M3Mzk4Njg0OTNkZjQ0ODAyOTYzMzFjOWY3YjVlZWYxNDM1NTlkN2RlNmQ5YThkMDcwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jQzcAvCuUV-0T6KF4VA8EgOWm4pSi46jREc5_DuRsvY)

看起来好像不是我这边的问题~~~

**Comment by xuexixuexijpg** [comment]
> > 拉源码看了下，为啥会少参数啊，这是Hilt的Bug吗？ ![image](https://private-user-images.githubusercontent.com/57759182/388323909-b51cb84e-827f-402a-8e4b-92e38517cbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTU4ODYsIm5iZiI6MTczMjE1NTU4NiwicGF0aCI6Ii81Nzc1OTE4Mi8zODgzMjM5MDktYjUxY2I4NGUtODI3Zi00MDJhLThlNGItOTJlMzg1MTdjYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MmZhNGZlYzZkY2M3Mzk4Njg0OTNkZjQ0ODAyOTYzMzFjOWY3YjVlZWYxNDM1NTlkN2RlNmQ5YThkMDcwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jQzcAvCuUV-0T6KF4VA8EgOWm4pSi46jREc5_DuRsvY)
> 
> 看起来好像不是我这边的问题~~~

我去Hilt那边问下，眼前只能改你这边的Compiler代码临时用下了=.=

**Comment by xuexixuexijpg** [comment]
> > 拉源码看了下，为啥会少参数啊，这是Hilt的Bug吗？ ![image](https://private-user-images.githubusercontent.com/57759182/388323909-b51cb84e-827f-402a-8e4b-92e38517cbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTU4ODYsIm5iZiI6MTczMjE1NTU4NiwicGF0aCI6Ii81Nzc1OTE4Mi8zODgzMjM5MDktYjUxY2I4NGUtODI3Zi00MDJhLThlNGItOTJlMzg1MTdjYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MmZhNGZlYzZkY2M3Mzk4Njg0OTNkZjQ0ODAyOTYzMzFjOWY3YjVlZWYxNDM1NTlkN2RlNmQ5YThkMDcwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jQzcAvCuUV-0T6KF4VA8EgOWm4pSi46jREc5_DuRsvY)
> 
> 看起来好像不是我这边的问题~~~

Hilt那边不理我估计忙于K2，大佬我将你的ComponentCompiler打成Jar包为什么没有将apache库打进去啊，导编译找不到依赖类，难道我打包姿势不对？

**Comment by xuexixuexijpg** [comment]
> > > 拉源码看了下，为啥会少参数啊，这是Hilt的Bug吗？ ![image](https://private-user-images.githubusercontent.com/57759182/388323909-b51cb84e-827f-402a-8e4b-92e38517cbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTU4ODYsIm5iZiI6MTczMjE1NTU4NiwicGF0aCI6Ii81Nzc1OTE4Mi8zODgzMjM5MDktYjUxY2I4NGUtODI3Zi00MDJhLThlNGItOTJlMzg1MTdjYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MmZhNGZlYzZkY2M3Mzk4Njg0OTNkZjQ0ODAyOTYzMzFjOWY3YjVlZWYxNDM1NTlkN2RlNmQ5YThkMDcwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jQzcAvCuUV-0T6KF4VA8EgOWm4pSi46jREc5_DuRsvY)
> > 
> > 
> > 看起来好像不是我这边的问题~~~
> 
> Hilt那边不理我估计忙于K2，大佬我将你的ComponentCompiler打成Jar包为什么没有将apache库打进去啊，导编译找不到依赖类，难道我打包姿势不对？

已自行解决了，我关了吧
