### ISSUE TITLE
是否考虑增加路由文档生成功能？

### ISSUE THREAD

**Issue by Bacchuc** [xiaojinzi123/Component#15]

**Comment by xiaojinzi123** [comment]
这个后续会支持的,暂时没有想好实现的方案

**Comment by xiaojinzi123** [comment]
从 1.8.0 开始已经支持生成文档了. 有需要请看 wiki 中的 [生成文档](https://github.com/xiaojinzi123/Component/wiki/%E6%96%87%E6%A1%A3%E7%94%9F%E6%88%90)
