### ISSUE TITLE
能否介绍一下无入侵式startActivityForResult的解决方案呢

### ISSUE THREAD

**Issue by ooftf** [xiaojinzi123/Component#17]

**Comment by xiaojinzi123** [comment]
在你用activity或者fragment传给框架跳转的时候,如果是forResult框架会在你的activity或者fragment中预埋一个特定的fragment，然后最终跳转的时候用这个特定的fragment去跳转。
这个可以参考 Rxpermission库，它用来解决申请权限的问题。原理都一样的，老哥

**Comment by xiaojinzi123** [comment]
而且采用这种方式能很好地支持第三方的库和系统的界面,结合[RouterAnno自定义Intent](https://github.com/xiaojinzi123/Component/wiki/RouterAnno%E6%B3%A8%E8%A7%A3#%E6%A0%87%E8%AE%B0%E5%9C%A8%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95%E4%B8%8A%E6%96%B9%E6%B3%95%E5%85%81%E8%AE%B8%E6%8A%9B%E5%87%BA%E4%BB%BB%E4%BD%95-exception)能完美的进行工作.
这是其他组件化框架没有的,也是此框架的其中一个突出的优点

**Comment by ooftf** [comment]
谢谢，等下实践一下

**Comment by xiaojinzi123** [comment]
> 谢谢，等下实践一下

不谢,有任何问题欢迎 issue
