### ISSUE TITLE
Cause: element == null

### ISSUE THREAD

**Issue by GimiZhang** [xiaojinzi123/Component#18]
配置完了 提示Cause: element == null 咋回事

**Comment by GimiZhang** [comment]
只要一运行就提示这个

**Comment by GimiZhang** [comment]
build也提示这个

**Comment by xiaojinzi123** [comment]
加群 870981195 方便解决您的问题

**Comment by GimiZhang** [comment]
嗯，好，问题已经解决了，关联错了，关联成androidx了

**Comment by xiaojinzi123** [comment]
> 嗯，好，问题已经解决了，关联错了，关联成androidx了

好的,有问题再 issue 或者加群里面问
