### ISSUE TITLE
支持组件间回调吗？

### ISSUE THREAD

**Issue by tanlzhi** [xiaojinzi123/Component#19]

**Comment by xiaojinzi123** [comment]
能说的具体一点吗？你说的比较抽象

**Comment by tanlzhi** [comment]
例如组件A启动组件B，B处理完成后返回数据到组件A。通常在一个组件内是通过一个callback接口来实现，组件之间支持类似用法吗？

**Comment by xiaojinzi123** [comment]
> 例如组件A启动组件B，B处理完成后返回数据到组件A。通常在一个组件内是通过一个callback接口来实现，组件之间支持类似用法吗？

首先确定一件事情,组件化方案就是解决两个没有依赖关系的业务组件之间的跳转和功能调用的,所以你说的肯定是支持的,分为两种情况
1. 如果你说的是界面和界面之间的,那么你看看 [跳转 wiki 中的拿 activityResult](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%B3%E8%BD%AC-%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%A0%81%E8%B7%B3%E8%BD%AC)的使用即可
2. 如果你说的不是界面之间,你可以使用[服务发现](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%A8%E6%A8%A1%E5%9D%97%E6%9C%8D%E5%8A%A1%E8%B0%83%E7%94%A8),去掉用其他模块的功能,至于是使用 callback 返回数据还是设计成类似于 RxJava 的 Observable 形式完全取决于你的服务接口的设计.

建议多看下 wiki 中的使用,应该能解决你的困惑!

**Comment by xiaojinzi123** [comment]
如果还有不懂的地方,建议加入 QQ 群来直接问.加群方式可以扫描项目主页最下方的二维码.
