### ISSUE TITLE
如何使用到自己得项目中呢

### ISSUE THREAD

**Issue by chinamingsss** [xiaojinzi123/Component#22]
你这个框架咋用到我自己得项目里呢？

**Comment by xiaojinzi123** [comment]
和使用平常的第三方库一样使用呀.
看文档配置成功就可以使用了呀

**Comment by chinamingsss** [comment]
文档在哪呢大神，，，，，，还有就是你这个框架支持远程仓库得方式吗？

**Comment by xiaojinzi123** [comment]
项目主页的 readme 就有呀
或者点击[此链接(wiki)](https://github.com/xiaojinzi123/Component/wiki/%E4%B8%BB%E9%A1%B5)

**Comment by chinamingsss** [comment]
你这个框架只是做了组件化里面得路由跳转是吗？路由如何自动生成呢？如果同事写了一个新页面，自己命名得host和path我不知道，拿如何才能跳转？难道要一个一个问吗或者一个一个得去查看代码吗？

**Comment by xiaojinzi123** [comment]
> 你这个框架只是做了组件化里面得路由跳转是吗？路由如何自动生成呢？如果同事写了一个新页面，自己命名得host和path我不知道，拿如何才能跳转？难道要一个一个问吗或者一个一个得去查看代码吗？

你这个问题问的优点懵逼啊.你对接后台接口的时候,如果后台不告诉你接口地址,难道你知道地址吗？
组件化的本质就是路由 + 跨组件调用
这两个方面此框架都是支持的.所以不是只是路由跳转
至于第一个问题,你应该问问你们团队应该怎么做好.
另外此框架还在考虑生成路由文档的功能,此功能能让每一个 `Module` 生成一个文档,可以让其他开发人员查看.
目前的版本的别人写的的路由只能你们手动先维护下.我们的项目所有的路由接口 path 都是写成基础的 `Module` 中维护的

**Comment by xiaojinzi123** [comment]
@chinamingsss 另外，host是可以省略的，让你写 host 是因为初期项目还没分modle的时候，你可以让所有界面现在路由的层面上分多个 module,以后代码分 module 了之后直接移动到对应模块就能工作，不用修改每一处使用的地方


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by chinamingsss** [comment]
知道了，大神！！！
