### ISSUE TITLE
十分中肯的讨论

### ISSUE THREAD

**Issue by robotAndroidCode** [xiaojinzi123/Component#24]
你好, 作者你这个项目除了生成文档这个功能没有, 我看其他方面都很好啊, 我也下载了 Demo 去使用了一下.

之前使用 `ARouter`, 后面发现还是有很多的不足的, 我们团队在思考是否可以使用你的这个框架.
因为 star 和热度都没有 `Arouter` 高, 我们团队需要用一些时间来考量这个项目. 希望在这段时间内坐着你可以给与帮助. 我们也会给出一些我们的建议

以下是这几天我们的一个建议：
1. 生成文档的功能希望还是要有的, 毕竟我们之前就是有的, 而且生成文档也免于我们手动维护
2. 在一些关键的功能上希望能更多的介绍下, 更便于大家熟悉
3. 我看 Demo 中很多都是 Router.with(context).... 这种形式的, 是不是加在最后的 `navigate` 方法上会更好?
4. 页面拦截器我感觉真的是一个很好地点, 这个解决了我们经常思考的一些痛点, 感谢。。
5. 在大型的 App 上, 通常会有各自的 Apk 最终打包成为一个, 那么独立运行这件事就很重要, 不知道作者你怎么考虑？
6. 作者你说的兼容性 100% 是依据什么得出的？

**Comment by xiaojinzi123** [comment]
首先谢谢支持

- 生成文档这个功能其实一直在计划中, 由于我的网页能力不太好, 所以一直比较拖, 之后加快开发吧
- wiki 的文档维护其实比较耗费我的时间, 我有空的时间我在补充一些到现在的 wiki 上, 现在的 wiki 其实介绍的也挺全了
- 你说的第三点我有想过, 其实只是使用层面上的一个不一样, 我觉得这个你克服一下吧, 因为如果放在 `navigate` 方法的参数上的话, 不说能带来什么用户体验, 我要改的东西太多了. 而且设计上可能都要动. 所以克服一下吧, 每个框架都有不一样的使用方式!
- 页面拦截器真的是一个神器, 不过使用还请细细斟酌, 切勿滥用
- `Component` 之所以 100% 兼容, 是因为 `Component` 不会去定制任何 `Gradle` 插件, 所有的代码和自己写的没啥两样！所以这里同时也回答了第 5 点, 我不认为独立运行一个 Module 是属于 `Component` 组件化框架的范畴, 这个功能还请另寻僻径, 和 `Component` 的使用无关
