### ISSUE TITLE
Router 跳转拿 ActivityResult 在只有 Application 的 Context 的时候, 如果使用？

### ISSUE THREAD

**Issue by robotAndroidCode** [xiaojinzi123/Component#25]
如题

**Comment by xiaojinzi123** [comment]
如果真的只有 Application 的 Context, 当然使用不了了, 因为 Component 贴近系统的设计, 系统在这个时候也是做不了的

但是如果你 App 是有界面在运行的, 其实你可以换个思路, 你可以拿到顶层的 Activity, 用它来跳转拿 ActivityResult, 这不就好起来了吗, 我们 App 就是这样弄的, 因为有时候在 Service 或者其他的代码中根本没有 Context 用, 这个思路就很好使!
