### ISSUE TITLE
跳转 Fragment 的问题

### ISSUE THREAD

**Issue by blackjuly** [xiaojinzi123/Component#27]
`ARouter` 有路由 `Fragment` 的功能, 其实说白了就是获取一个 `Fragment`. 

我看了你的源代码, 我发现你这里是完全把获取 `Fragment` 当成是服务发现的一部分, 我个人觉得从原则上看确实是属于服务发现的一部分, 但是获取 `Fragment` 是一个比较常用的功能. 是否能考虑像 `ARouter` 一样做一个 `路由Fragment` 的功能. 方便获取 `Fragment`. 我个人感觉这样子会比较方便. 毕竟很多时候, 一个 `Activity` 可能对应着很多个 `Fragment`.

**Comment by xiaojinzi123** [comment]
后续有这个打算来着, 因为获取 `Fragment` 虽然属于 `SPI` 的范畴, 但是确实应该有更方便的获取方式. 这个在之后的版本中我会计划加入的, 大致的使用就是：
```
Fragment fragment = Router.navigateFragment(String fragmentFlag) 
```

**Comment by xiaojinzi123** [comment]
新版本 1.7.6 中已经有这个功能了, 还请查看

使用方式：[跳转 Fragment](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%B3%E8%BD%AC-Fragment)

**Comment by blackjuly** [comment]
收到，我去瞧瞧
