### ISSUE TITLE
全局拦截器的问题

### ISSUE THREAD

**Issue by robotAndroidCode** [xiaojinzi123/Component#28]
我现在有一个拦截器, 它是很多地方用到的. 比如登陆拦截器, 就像你的源码中, 你是放到了 User 模块. 我能否直接放到 Base 中. 看上去使用还方便些. 希望能给些建议

**Comment by xiaojinzi123** [comment]
我个人觉得这个问题很好解决. 假如我们不考虑任何其他因素, 我们就考虑这个拦截器是属于哪一个 Module 的, 那相信你一定可以判断出来, 判断不出来的那些你可以放到 Base, 等到你想到了再转移都是 ok 的

既然你可以想清楚拦截器属于哪个模块, 那我是建议你把对应的拦截器放到对应的模块中. 反正 Component 框架也提供了跨组件使用其他模块的拦截器的功能. 
比如登录拦截器、定位拦截器, 很多地方都会用到, 但是他们一个属于 User 模块, 一个属于(地图、Tools等等, 看你项目把这个功能归到哪个模块) 模块. 那你完全可以在各自的模块中去写, 这样子也更符合代码的边界的划分, 不会啥东西都往 base 上面放
