### ISSUE TITLE
代码警告报黄问题

### ISSUE THREAD

**Issue by Bacchuc** [xiaojinzi123/Component#31]
![image](https://user-images.githubusercontent.com/20861058/67016721-3cf3a900-f12b-11e9-8448-61750a640495.png)

如上所示，代码报黄，引起的原因是最后 subscribe 方法提示返回值需要处理

**Comment by xiaojinzi123** [comment]
其实这个不是我的框架的问题,  你发现没有最后你拿到的是 RxJava 的 Single 去调用 subscribe 方法, 他的方法有一个注解 @CheckResultReturn. 导致报黄

**Comment by Bacchuc** [comment]
好滴O(∩_∩)O谢谢！希望这里可以优化一下就更胖了！
