### ISSUE TITLE
你的 Idea 插件不支持跳转到 Fragment 呀

### ISSUE THREAD

**Issue by robotAndroidCode** [xiaojinzi123/Component#33]
```
Fragment fragment = Router.with("testFragment").navigate();
```

这句能添加一个快捷跳转吗?

**Comment by xiaojinzi123** [comment]
帮你纠正了提的问题的名称, 我的是 Idea Plugin 不是 Gradle 插件

另外你的这个问题, 我会再之后的更新中加上, 时间暂时不定,  但是一定不会太久, 请放心

**Comment by lcyluo** [comment]
插件好像用了RxRouter也没有跳转标识

**Comment by xiaojinzi123** [comment]
> 插件好像用了RxRouter也没有跳转标识

请确认你的 idea plugin 版本是 1.2.4 最新版.

如果插件安装了还是没有提示, 建议你尝试以下几个动作：

1. 如果你的目标标记的 Activity 出现了如下的图标, 说明插件是 ok 的, 你对不出现图标的界面关闭再打开试试, 应该能解决
![image](https://user-images.githubusercontent.com/12975743/67448294-211b6600-f649-11e9-83f2-bee1bb253125.png)

2. 如果你的所有地方都没有出现图标, 建议你卸载插件重装. 部分没有的情况都是代码缓存引起的, 对应界面关闭再打开就有了. 

如果再有问题, 还请加群, 更快速的帮你解决问题

**Comment by lcyluo** [comment]
目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！

**Comment by xiaojinzi123** [comment]
> 目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！

1.2.4 我已经发布有一些时候了, 当时就是修复 RxRouter 的问题的.

如果你不嫌麻烦的话, 你可以去 [此处](https://plugins.jetbrains.com/plugin/12519-routergo/versions) 手动下载

然后我去研究下会啥最新的只能搜索到 1.2.2

**Comment by xiaojinzi123** [comment]
> 目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！

好像是 idea 版本的产生的兼容性问题导致能搜到的不一样. 这个问题我会尽快解决的.
感谢你选择 Component

**Comment by lcyluo** [comment]
> > 目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！
> 
> 好像是 idea 版本的产生的兼容性问题导致能搜到的不一样. 这个问题我会尽快解决的.
> 感谢你选择 Component

嗯，下载了你的插件，安装时也是提示不兼容AndroidStudio 3.5.1，感谢你的支持！

**Comment by lcyluo** [comment]
> > > > 目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！
> > > 
> > > 
> > > 好像是 idea 版本的产生的兼容性问题导致能搜到的不一样. 这个问题我会尽快解决的.
> > > 感谢你选择 Component
> > 
> > 
> > 嗯，下载了你的插件，安装时也是提示不兼容AndroidStudio 3.5.1，感谢你的支持！
> 
> 很不好意思带来不便, 但是不干扰你正常的编码. 这个问题我会尽快的修复的. 修复好了我来这里告诉你

嗯，这个都是小事情，你这边空了处理都OK；

**Comment by xiaojinzi123** [comment]
> > > > > 目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！
> > > > 
> > > > 
> > > > 好像是 idea 版本的产生的兼容性问题导致能搜到的不一样. 这个问题我会尽快解决的.
> > > > 感谢你选择 Component
> > > 
> > > 
> > > 嗯，下载了你的插件，安装时也是提示不兼容AndroidStudio 3.5.1，感谢你的支持！
> > 
> > 
> > 很不好意思带来不便, 但是不干扰你正常的编码. 这个问题我会尽快的修复的. 修复好了我来这里告诉你
> 
> 嗯，这个都是小事情，你这边空了处理都OK；

你的 Android Studio 应该是 3.5 的吧, 官方目前出了 3.5.1 的稳定版本。 之前为了满足大量的 3.4 的用户. 现在看起来, 3.4 的都可以用新的 3.5.1 了, 那我这边改下兼容的版本号. 
我这里确认下你是在 3.5 + 上搜索不到最新版本的对吧？

**Comment by lcyluo** [comment]
> > > > > > 目前最新能搜索到的插件版本为1.2.2，1.2.4版本目前搜索不到。非常感谢你的帮助！
> > > > > 
> > > > > 
> > > > > 好像是 idea 版本的产生的兼容性问题导致能搜到的不一样. 这个问题我会尽快解决的.
> > > > > 感谢你选择 Component
> > > > 
> > > > 
> > > > 嗯，下载了你的插件，安装时也是提示不兼容AndroidStudio 3.5.1，感谢你的支持！
> > > 
> > > 
> > > 很不好意思带来不便, 但是不干扰你正常的编码. 这个问题我会尽快的修复的. 修复好了我来这里告诉你
> > 
> > 
> > 嗯，这个都是小事情，你这边空了处理都OK；
> 
> 你的 Android Studio 应该是 3.5 的吧, 官方目前出了 3.5.1 的稳定版本。 之前为了满足大量的 3.4 的用户. 现在看起来, 3.4 的都可以用新的 3.5.1 了, 那我这边改下兼容的版本号.
> 我这里确认下你是在 3.5 + 上搜索不到最新版本的对吧？

是的，最新版本为3.5.1，正在使用这个版本；

**Comment by xiaojinzi123** [comment]
@lcyluo  插件已经提交, 已经在审核了, 如果你比较急, 你可以点击这里 [下载](https://github.com/xiaojinzi123/RouterGoPlugin/releases/download/v1.2.4/RouterGoPlugin-1.2.4-3.5+.jar) 
给你带来不便, 还请谅解

**Comment by lcyluo** [comment]
> @lcyluo 插件已经提交, 已经在审核了, 如果你比较急, 你可以点击这里 [下载](https://github.com/xiaojinzi123/RouterGoPlugin/releases/download/v1.2.4/RouterGoPlugin-1.2.4-3.5+.jar)
> 给你带来不便, 还请谅解

已经更新最新版本1.2.5，非常感谢！

**Comment by mikeliu60** [comment]
作者您好，我的as是3.6版本的，这个idea插件装不上，您什么时候有空可以适配一下吗

**Comment by xiaojinzi123** [comment]
你在 Idea 的插件仓库中搜索不到此插件是吗？我记得我的 as 也3.6了。好像能使用的。
另外这个插件只是一个辅助工具，我没有花很多精力去维护，所以这个插件的版本更新可能较慢。当然了，我有空就会支持的。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by mikeliu60** [comment]
对，我在market中搜不到

**Comment by xiaojinzi123** [comment]
AS 3.6 RC 候选版本已经发布了 [1.2.6](https://github.com/xiaojinzi123/RouterGoPlugin/releases/tag/v1.2.6)
多两天可以在商店搜索下载. 支持了 Fragment 的正向跳转. 反向的后续会支持的. 
等不到商店上线可以直接点击上面的链接自行下载 jar 包安装即可
