### ISSUE TITLE
requestCode没写的时候没有错误日志！不方便排查~

### ISSUE THREAD

**Issue by hua407035000** [xiaojinzi123/Component#36]
requestCode没写的时候没有错误日志！不方便排查~

**Comment by xiaojinzi123** [comment]
> requestCode没写的时候没有错误日志！不方便排查~

预计新版本 1.7.7.2 会修复这个日志问题. 出现的时机是跳转拿 ActivityResult 有关的方法才会有这个情况. 比如 `forwardForIntent` 方法.
