### ISSUE TITLE
跳转fragment:内存泄漏

### ISSUE THREAD

**Issue by Zengyonghao** [xiaojinzi123/Component#39]
如图
![8E)3}L9Z{A0N 8C@%ZR $FJ](https://user-images.githubusercontent.com/17347430/68842315-24ae8400-0701-11ea-9fb0-f8e649d4a687.png)

**Comment by xiaojinzi123** [comment]
老哥, 你的图我看不到呀
![image](https://user-images.githubusercontent.com/12975743/68842657-ae5e5180-0701-11ea-817e-f564252d0a8b.png)

**Comment by xiaojinzi123** [comment]
你是单例的形式是吧? 这个在框架中本身就会一直引用着, 这个不算内存泄露吧.
因为你下次获取还是会获取到同一个 Fragment.
如果算是一个问题, 那我这边看下后续的一个解决方式, 主要还是看你是否认为这是一个问题。还请您答复一下

**Comment by xiaojinzi123** [comment]
我忽然想到, Fragment 当时为什么默认是不是单例的, 就是考虑到以下几点：

1. 一般我们获取一个 Fragment 到使用, 一般都是 new 一个的.
2. 如果一个 Fragment 是一个单例的, 其实你也不能显示到俩个 Activity 上. 这是不对的..... 

所以你这个 issue 我倒是考虑后面把是否单例那个属性给去掉。。。

**Comment by Zengyonghao** [comment]
> 你是单例的形式是吧? 这个在框架中本身就会一直引用着, 这个不算内存泄露吧.
> 因为你下次获取还是会获取到同一个 Fragment.
> 如果算是一个问题, 那我这边看下后续的一个解决方式, 主要还是看你是否认为这是一个问题。还请您答复一下

是的 我使用 **singleTon**标记了这些Fragment 
我想我可以理解这个问题产生的原因了
