### ISSUE TITLE
不支持kotlin的object类中的方法

### ISSUE THREAD

**Issue by Zengyonghao** [xiaojinzi123/Component#40]
objcet类在编译的时候生成的是静态instance对象
导致generatedJava生成的时候编译报错

**Comment by Zengyonghao** [comment]
> objcet类在编译的时候生成的是静态instance对象
> 导致generatedJava生成的时候编译报错

临时解决方法
在路由注解的方法上添加@JvmStatic注解 
将其视为java的静态方法

**Comment by xiaojinzi123** [comment]
能解决就行, 这个我也没有考虑到. 
反正就是在原有基础上加上一个 @JvmStatic 就可以了. 代码就能编译通过了.
