### ISSUE TITLE
requestCode 变化的问题?

### ISSUE THREAD

**Issue by Bacchuc** [xiaojinzi123/Component#41]
在一个界面中, 我只要用一次框架提供的获取 ActivityResult 的跳转之后, 
后续我使用 如下代码跳转之后, 在 onActivityResult回调中的 requestCode 都是不对的, 不是下面我传递的那个值！！！

```
Router
      .with(this)
      .host("user")
      .path("address")
      .requestCode(100)
      .forward();
```

不用获取 ActivityResult 的跳转就没有问题

**Comment by xiaojinzi123** [comment]
这个问题我复现了, 我清楚了. 谢谢反馈。

下个版本将会修复. 发布了我会在这里通知. 不过你们用以下方式避免一下：

跳转拿 ActivityResult 和 普通跳转携带 requestCode 不要混用. 暂时可以避免这个问题的出现.

**Comment by Bacchuc** [comment]
好滴，谢谢
