### ISSUE TITLE
这个库可以和Fragmentation一起使用吗

### ISSUE THREAD

**Issue by Alvazz** [xiaojinzi123/Component#42]
不知道这个库是否可以与Fragmentation一起使用，主要不了解Fragment到跳转会不会引发冲突。

还望作者解答，谢谢啦。

**Comment by Alvazz** [comment]
Fragmentation指的是这个：https://github.com/YoKeyword/Fragmentation

**Comment by xiaojinzi123** [comment]
本库提供 Androidx 和 非 Androidx, 和任何一个框架没有兼容性问题.

**Comment by Alvazz** [comment]
@xiaojinzi123 谢谢
