### ISSUE TITLE
接入文档有点儿不清晰啊

### ISSUE THREAD

**Issue by showkiwi** [xiaojinzi123/Component#43]
按照文档加入依赖以后没法用啊，根本找不到Component这些，是还需要安装什么插件之类的吗

**Comment by xiaojinzi123** [comment]
> 按照文档加入依赖以后没法用啊，根本找不到Component这些，是还需要安装什么插件之类的吗

不可能的呀.  你填写了依赖之后, 编译都成功了？
最好贴出你的依赖和初始化的代码. 没图没真相. 而且文档中写的没问题. 请你仔细核对

**Comment by xiaojinzi123** [comment]
没啥问题的这个 issue 关闭啦, 有需要再来开启
