### ISSUE TITLE
能不能开放一个getIntent的方法，我消息栏需要拿对应路由的Intent很难受。

### ISSUE THREAD

**Issue by cqray** [xiaojinzi123/Component#44]
能不能开放一个getIntent的方法，我消息栏需要拿对应路由的Intent很难受。
只能在RouterCenter中，反射拿到对应的Intent。
还是我没有找对地方？

**Comment by xiaojinzi123** [comment]
> 能不能开放一个getIntent的方法，我消息栏需要拿对应路由的Intent很难受。
> 只能在RouterCenter中，反射拿到对应的Intent。
> 还是我没有找对地方？

首先先明确告诉你, 你这种拿 `Intent` 去自己跳转, 本身就违背了框架用 Host + Path 去代替一个目标. 
你这种情况想要拿到 `Intent` 不能通过路由, 你得通过服务发现. 

```
Intent intent = ServiceManager.get(xxx.class).getXXXIntent();
```

一个构建好的 `Intent` 是一个确定的界面. 但是一个确定的 host + path 可能是不同的 `Intent`.

比如你利用 order/detail?orderId=123 . 然后你利用拦截器对请求拦截, 用 123 去访问服务器, 根据订单类型你需要跳转到不同的界面. 这时候一个 url 就对应了不同的 `Intent`. 

当然了这种情况很少见. 我只是告诉你你用我的框架拿 `Intent` 是不可能的. 我不会有此类的接口. 也不允许你自己用反射去获取. 遇到此类情况, 最好在这里提 `issue` 或者进去问我就行.

**Comment by LinXueyuanStdio** [comment]
我也希望有Intent。比如点击通知栏的通知跳转，点击小部件跳转，都需要PendingIntent，这是 Android 提供的API决定的。现在临时的解决方法是加入无界面的中转 Activity 来解决。但是感觉临时方法不优雅。

**Comment by xiaojinzi123** [comment]
服务发现的使用：[点我查看文档](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%A8%E6%A8%A1%E5%9D%97%E6%9C%8D%E5%8A%A1%E8%B0%83%E7%94%A8)

**Comment by xiaojinzi123** [comment]
> 我也希望有Intent。比如点击通知栏的通知跳转，点击小部件跳转，都需要PendingIntent，这是 Android 提供的API决定的。现在临时的解决方法是加入无界面的中转 Activity 来解决。但是感觉临时方法不优雅。

使用服务发现.  换句话说就是你自己用普通的代码获取到任何一个你想要的 `Intent`. 相当于你直接拿到了目标的 `Intent`. 未尝不可呢.
服务发现的使用：[点我查看文档](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%A8%E6%A8%A1%E5%9D%97%E6%9C%8D%E5%8A%A1%E8%B0%83%E7%94%A8)

**Comment by xiaojinzi123** [comment]
> 我也希望有Intent。比如点击通知栏的通知跳转，点击小部件跳转，都需要PendingIntent，这是 Android 提供的API决定的。现在临时的解决方法是加入无界面的中转 Activity 来解决。但是感觉临时方法不优雅。

我饭后细细的思考了这个问题. 其实你的无界面 `Activity` 倒是也是一个好的解决方式. 这样, 你的 `Intent`   只要带上目标界面的 url, 然后在无界面 `Activity` 中拿到 `url` 直接使用 `Router` 跳转. 我觉得不错呀. 这样子所有的路由就都可以囊括到 `Router` 的范围, 并且得到所有的 `Router` 优势. 比如页面拦截器(假如目标界面需要登陆或者定位啥的)...

**Comment by xiaojinzi123** [comment]
两位可以的话, 扫码进去讨论吧. 我打算看下是否可以在框架的层面上帮助你们解决这个问题. 
但是我今天在使用无界面的 `Activity` 作为过渡的载体的时候, 发现无界面的 `Activity` 必须在 oncreate 之后就调用 `finish` 方法, 所以我一时想不明白 @LinXueyuanStdio 这位兄台你是怎么做的.

**Comment by LinXueyuanStdio** [comment]
大概是
onCreate(){
    url = getFromIntent(getIntent());
    Router.go(url);
    finish();
}
在onCreate里调用finish()，这样浪费的资源少

**Comment by xiaojinzi123** [comment]
> 大概是
> onCreate(){
> url = getFromIntent(getIntent());
> Router.go(url);
> finish();
> }
> 在onCreate里调用finish()，这样浪费的资源少

首先我确定一个点就是你这种无界面的做法是 ok 的, 我本打算是否可以框架来提供这种无界面的 Activity. 但是发现我不能随意定制你们的无界面 Activity 要做的事情. 所以这部分还是打算开发者自己去实现吧.

另外你额外注意一点, 用 Component 跳转,  finish() 方法调用的时候一定要注意. 如果你跳转用的是无界面 Activity 作为 Context, 那么一定要在回调中去调用 finish() 否则路由会被取消.
或者你可以省略传入 Context, 默认会使用 Application.

**Comment by xiaojinzi123** [comment]
各位, 你们的这个问题, 自从提出, 我便一直在研究, 想在框架层面上提供一个好的方式给你们带去方便. 并且解决你们目前的问题. 
很高兴我目前在 develop 分支上解决了你们的问题. 在源码中的示例代码 `MainAct` 中我增加了两个按钮, 分别可以创建一个消息, 点击消息都是跳转到一个需要登录的界面. 效果上已经完美的解决了你们的问题. 
框架提供了一个默认的无界面的代理 `Activity` 来做的, 你们使用是无感的. 另外这个默认的代理 `Activity` 是可以指定成你们自定义的 `Activity` 的. 更多的信息还请看源码中的示例代码的 MainAct 中的代码. 我觉得会对你们有很大的帮助.
如果你们觉得此方式合理并且能接受, 我将在下个版本发布, 版本随时可以发布. 如果可以的话我想让你们拉取 develop 分支看看效果和使用方式是否你们能够接受

**Comment by LinXueyuanStdio** [comment]
看了代码，觉得OK

**Comment by xiaojinzi123** [comment]
两位, 新的版本 1.7.7.3 已经发布了. 你们两位的问题. 可以具体[点击这里](https://github.com/xiaojinzi123/Component/wiki/ProxyIntent) 查看解释和使用方式哦. 此 issue 就先关闭了呦, 有需要欢迎继续讨论
