### ISSUE TITLE
怎么跨module使用service？

### ISSUE THREAD

**Issue by showkiwi** [xiaojinzi123/Component#46]
怎么跨module使用service？启动service，或者绑定service

**Comment by xiaojinzi123** [comment]
如果是本模块的, 你能理解. 
如果你要用的功能是其他模块的, 那你应该使用 [ 接口 + 实现 ](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%A8%E6%A8%A1%E5%9D%97%E6%9C%8D%E5%8A%A1%E8%B0%83%E7%94%A8) 的跨模块调用去调用你想要的方法呀 

又或者你觉得这的 Service 是公用的, 那你放到 Base 中呗.

**Comment by showkiwi** [comment]
没懂～那我怎么通过intent给service传递数据呢，跨module的话，还是只能通过接口+实现做？

**Comment by xiaojinzi123** [comment]
> 没懂～那我怎么通过intent给service传递数据呢，跨module的话，还是只能通过接口+实现做？

首先, 你组件化了之后. 其实最最关键的就是跨模块调用其他模块的功能. 而因为路由在 Android 中是比较重要的, 所以很多框架都会涉及路由的部分. 这就是你看到的基本上的框架都有两个主要功能：

- 跨模块调用
- 路由

而你现在的问题是, 如何使用其他模块的 `Android` 原生的 `Service`.  你这个问题换句话说就是跨模块调用其他模块的功能. 我给你比喻一个例子：

假如现在有两个 `Module`, 一个模块是 `User` 模块, 另一个是 `Download` 模块.

现在 `User` 模块想下载一个文件, 但是这部分功能应该是 `Download` 模块做的. 所以这时候, 就让 `Download` 模块提供出一个 `接口` 出来让 `User` 模块使用. 而这个接口的实现是 `Download` 模块实现的, 实现中你可能用到了`Android` 原生的  `Service` 去下载. 

上面 `User` 模块丝毫不知道最终的实现是如何的, 只知道调用了一个接口. 
而  `Download`  则负责包装一些功能给其他模块使用. 

换言之, 如果有其他模块需要完成登陆, 那么就需要 `User` 模块提供登陆相关的接口给其他模块使用.

我觉得我说的够明白了. 如果还不明白, 我觉得你需要再理解一下什么是模块之间的解耦.
