### ISSUE TITLE
Used Android.mk to compile Component

### ISSUE THREAD

**Issue by gospeljohn** [xiaojinzi123/Component#48]
@xiaojinzi123 , Component项目是否支持通过Android.mk方式编译？谢谢

**Comment by xiaojinzi123** [comment]
> @xiaojinzi123 , Component项目是否支持通过Android.mk方式编译？谢谢

你引用我的库这是没有编译过程的. 直接用就行. 
但是我有生成代码的 `注解驱动器` 得 Gradle 来驱动的. `.mk` 中能使用注解驱动器吗？这个我不太清楚. `.mk` 的构建方式我记得很老了. 
只要你能让 `注解驱动器` 生效, 就可以

**Comment by gospeljohn** [comment]
谢谢，好像Android的Soong编译环境支持注解驱动，我再研究研究
