### ISSUE TITLE
通过系统浏览器打开页面的问题

### ISSUE THREAD

**Issue by caprice** [xiaojinzi123/Component#49]
一个很常见的场景，分享某个页面到微信，其点击分享跳转地址为：router://app/main。
如果采用Manifest.xml中用
```xml
   <data
              android:host="app"
              android:pathPrefix="/main"
              android:scheme="router" />
```
方式，大部分系统浏览器是能识别router://app/main并打开app到对应页面的。
然而如果采用Component，是不识别的

**Comment by xiaojinzi123** [comment]
先解释一下。Component 是一个设计和使用都贴近系统的组件化框架。路由模块尤其强大。和你图中的没有关系。但是两者可以产生关系。
比如你用图中的方式声明一个代理 Activity, 所以外部跳转都跳转到代理界面。然后传递 url 过来让代理界面发起跳转即可。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by caprice** [comment]
你说的没问题。
经测试下面配置能让浏览器识别，但是manifest中的host必须是*.*的格式如app.com或com.app：
![image](https://user-images.githubusercontent.com/2981114/72720494-16735d00-3bb5-11ea-9ce2-ddb557c8b5b1.png)
然而你build.gradle配置的路由如果同样设置为app.com或com.app就会报错：
![image](https://user-images.githubusercontent.com/2981114/72720747-98638600-3bb5-11ea-9182-7ac1b39f2add.png)

**Comment by xiaojinzi123** [comment]
我说的是, 你用如下的配置先配置一个可以外部跳转的 `ProxyActivity`. 

```xml
<activity
            android:name="com.xiaojinzi.componentdemo.view.ProxyAct"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data 
                android:host="app.com"
                android:pathPrefix="/proxy"
                android:scheme="testProject" />
						</intent-filter>
</activity>
```

然后你分享出去的链接是：testProject://app.com/proxy?uri=xxx

其中 `xxx` 是你真正的路由 `Uri` ："router://user/info?userId=123". 当然这个 `Uri` 的值替换 `xxx` 的时候肯定要经过 `UrlEncode`. 

外部跳转到你的 `ProxyAct` 之后, 你拿到传递过来的 `Uri`, 比如就是你上面的 "router://user/info?userId=123". 然后发起跳转即可.

```java
public class ProxyAct extend Activity {
			oncreate(){
        	String url = getIntent().getString("uri","默认的Router Uri")
          // 发起跳转
          Router.with(this)
            		.url(uri)
            		.forward();
      }
}
```

**Comment by caprice** [comment]
你的意思我一开始就懂。我也知道可以这么做。目前之所以考虑接入路由框架，还是想改造老项目的。
老项目的分享出来的数据就是router:/app.com/userDetail?userId=123. 是不能换成 android:scheme="testProject"类似这种的。可能唯一能做的就是ProxyAct对应
  <data
                    android:host="app.com"
                    android:scheme="router" />

然后在
```java
public class ProxyAct extend Activity {
			oncreate(){
        	String url = getIntent().getString("uri","默认的Router Uri")
          url=url.replace("router://app.com", "router://app")
          // 发起跳转
          Router.with(this)
            		.url(uri)
            		.forward();
      }
}
```
但这种代码明显不是一个好的方法。

**Comment by xiaojinzi123** [comment]
你的意思我也理解. 主要是 `Component` 是不能去接管系统的功能的, `Component` 也不会这么去做. 
如果你分享出去的链接不用代理界面. 都是如下的形式的：
- router:/app.com/userDetail?userId=123
- router:/order.com/detail?orderId=xxx
- ......
那么可能不太适合用 `Component`, `Component` 不会去做 `Hook` 的事情. 那你再考虑一下选型的问题呗

**Comment by caprice** [comment]
另一个类似华为推送，小米推送点击通知设置的跳转地址也会是router:/app.com/userDetail?userId=123这种，打开指定页面，如果首页没启动，则打开详细页，首页等。类似的需求其实也还算比较普遍的。Component可以考虑这些进去的。另外上面Component自定义还是要能自由支持类似app.com这种格式的。一个优秀的框架出来不易，作者加油

**Comment by xiaojinzi123** [comment]
> 另一个类似华为推送，小米推送点击通知设置的跳转地址也会是router:/app.com/userDetail?userId=123这种，打开指定页面，如果首页没启动，则打开详细页，首页等。类似的需求其实也还算比较普遍的。Component可以考虑这些进去的。另外上面Component自定义还是要能自由支持类似app.com这种格式的。一个优秀的框架出来不易，作者加油

我再次强调一点：如果你能拿到 "router:/app.com/userDetail?userId=123" 这种`Uri` 的, 那么就不是问题了. `Component` 本就支持通知栏点击的跳转. 这个具体看源码中的示例.

`app.com` 这种有特殊符号的做一个支持, 首先这个是没问题的. 如果解决这个就能给你带去方便, 那么我可以近期就可以发个版本支持. 
问题是解决不了你一开始说的支持 `<intent-filter>` 的这种声明. 我还是要说, 那是系统的东西, 我没法 `Hook`, 我也不会去 `Hook`, 因为 `Hook` 会增加 `Component` 的不稳定性. 
`Component` 和 `<intent-filter>` 的这种声明目前是一点关系都没有的. 不出意外未来也不会有. 

总结一下你全部的问题：
- 支持  `<intent-filter>` , 暂时不会做这种支持
- 支持 `app.com`. 完全可以. 下个版本就可以
- 支持通知栏跳转. 本就支持. 这个自行看源码或者 `wiki` 中的 `ProxyIntent`

**Comment by caprice** [comment]
明白了，谢谢

**Comment by xiaojinzi123** [comment]
@caprice 兄弟, 我试了一下, 你分享出去的那些链接是可以的呀. 

比如你分享出去的链接为："component://com.xiaojinzi/test?name=xiaojinzi" 

然后你新建了一个 `ProxyActivity`. 清单文件配置如下：

```xml
<activity android:name=".view.ProxyAct">
    <intent-filter>
        <data
              android:scheme="component" />
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
    </intent-filter>
</activity>
```

那你所有 `scheme`  为 `component` 都会被启动启动到  `ProxyAct` 界面. 

在界面中获取 `Uri` 信息为 "component://com.xiaojinzi/test?name=xiaojinzi" . 

然后通过 `Component` 发起跳转就可以了呀. 我试过了, 可以拿到的. 可以是你利用上面的配置配置了一个统一经过的 `Activity` . 你看下是否可以满足你的要求
