### ISSUE TITLE
希望Fragment的获取可以增加更多样化的put形式

### ISSUE THREAD

**Issue by Zengyonghao** [xiaojinzi123/Component#53]
**current**:

![U OL`X VV~1}S6NDA1JJ`PD](https://user-images.githubusercontent.com/17347430/76405625-5f7cac00-63c3-11ea-8a9b-02200db4df41.png)

**hope**：
```
putString()
putInt()
....
```

**Comment by xiaojinzi123** [comment]
怕了怕了, 不怕苦不怕累发了一个版本. 1.8.0.2 已经支持了.
