### ISSUE TITLE
采用component_impl_rx 

### ISSUE THREAD

**Issue by ganzhex2019** [xiaojinzi123/Component#55]
在application 中初始化的时候   出现如下报错：java.lang.NoClassDefFoundError: com.xiaojinzi.component.support.RxErrorConsumer

**Comment by ganzhex2019** [comment]
还有就是怎么单独调试一个模块， 比如说 即时通讯模块 ， 需要在Applicaltion中初始化一些三方库，那么这个时候怎样让即时通讯中的Application融合到 app壳模块中？  大佬  指点下

**Comment by xiaojinzi123** [comment]
> 在application 中初始化的时候 出现如下报错：java.lang.NoClassDefFoundError: com.xiaojinzi.component.support.RxErrorConsumer
你是否依赖了 `RxJava`, 如果没有的话依赖一下. 版本号都是你自己决定的. 
依赖 `RxJava2` 的任何一个版本

**Comment by xiaojinzi123** [comment]
> 还有就是怎么单独调试一个模块， 比如说 即时通讯模块 ， 需要在Applicaltion中初始化一些三方库，那么这个时候怎样让即时通讯中的Application融合到 app壳模块中？ 大佬 指点下

看这个吧, [走你](https://github.com/xiaojinzi123/Component/wiki/%E4%B8%9A%E5%8A%A1%E7%BB%84%E4%BB%B6%E5%8D%95%E7%8B%AC%E8%BF%90%E8%A1%8C)

**Comment by ganzhex2019** [comment]
是的。试了下。rxjava2没问题。rxjava3有问题。应该是rxjava3把这些异常取消了。 没来得及看rxjava3源码

xiaojinzi123 <notifications@github.com>于2020年3月24日 周二09:11写道：
