### ISSUE TITLE
关于flutter的支持

### ISSUE THREAD

**Issue by LuodiJackShen** [xiaojinzi123/Component#56]
您好，我看到介绍说componet是支持flutter混合跳转的，但是没找到具体的文档，这块能详细介绍下吗？

**Comment by xiaojinzi123** [comment]
`flutter`、`H5` 只要能和原生交互的. 都能跳转到原生界面.  原生跳 `flutter`、`H5` 的话,  `H5` 由于需要原生的界面作为载体, 所以也在跳转范围之内.  跳转到 `flutter` 界面不太清楚. 本人没有太多涉猎.
但是 `flutter`、`H5` 和原生能交互就一定能跳转到原生界面.

这里举例 `H5`, 使用 @JavascriptInterface 让 `H5` 能调用到以下方法, 一个 `Url` 中包含了目标 + 携带的参数.  如下代码便实现了统一跳转, 并且目标界面的进入的前置跳转由 `页面拦截器` 完成. 比如你想打开的界面为系统电话界面. 你的 `Url` 为 "router://system/callPhone?tel=1581579xxxxx". 目标界面的页面拦截器会处理好进入前的权限申请等操作. (这个页面拦截器需要自己实现哦. 可以参看源码中的 `Demo`). 这样子你就无需理会进入目标界面的任何前置条件了. 包括：`登陆`、`权限`、`定位`、`其他任何的需求`

```
@JavascriptInterface
public void openUrl(final String url) {
    Router.with(this).url(url).forward();
}
```

**Comment by LuodiJackShen** [comment]
谢啦，我想我明白你的意思了。
