### ISSUE TITLE
关于requestCode的问题

### ISSUE THREAD

**Issue by MarkMjw** [xiaojinzi123/Component#57]
这样一个场景：A通过Router+requestCode跳转B，B又跳转了C，然后C返回B，B返回A，此时A收不到onActivityResult。

**Comment by xiaojinzi123** [comment]
不会呀. 你怎么写的. 代码能贴一下吗?

**Comment by MarkMjw** [comment]
> 不会呀. 你怎么写的. 代码能贴一下吗?

稍等，我弄个Demo试试，项目代码流程太复杂了。

**Comment by xiaojinzi123** [comment]
我也再次用代码确认了一遍. 是没问题的哦. 你现在排查一下其他情况吧.

**Comment by MarkMjw** [comment]
> 我也再次用代码确认了一遍. 是没问题的哦. 你现在排查一下其他情况吧.
> 想到的一个可能的原因：跳转 B 界面的时候的启动模式问题

我发普通跳转都不行，哪里使用有问题吗？
A->B
`Router.with(this@DebugActivity).hostAndPath("app/test").requestCode(100).forward()
`
B结束时：
`override fun finish() {
        setResult(Activity.RESULT_OK)
        super.finish()
}`

**Comment by MarkMjw** [comment]
> ```kotlin
>         setContentView(R.layout.activity_debug)
> ```

将A代码改成如下形式，可以收到result，但是requestCode不正确，callback里面收到requestCode=100，onActivityResult中的requestCode=65636：

```kotlin
Router.with(this@DebugActivity)
                    .hostAndPath("app/test")
                    .requestCode(100)
                    .forwardForResult(object : BiCallback<ActivityResult> {
                        override fun onSuccess(result: RouterResult, t: ActivityResult) {
                            Log.w("test", "${t.requestCode} ${t.resultCode}")
                        }

                        override fun onCancel(originalRequest: RouterRequest?) {
                        }

                        override fun onError(errorResult: RouterErrorResult) {
                        }
                    })
```

**Comment by xiaojinzi123** [comment]
上面你的 forward 本就是普通跳转, 不是 startActivityForResult.
下面你的 forwardForResult 用对了. 但是你说 requestCode 对不上, 因为你不能混着用的. 你不能让我框架去接受, 你又自己去接受. 因为实现这个功能其实内部预埋了一个 Fragment 去 startActivityForResult 的, 所以你在你的 Activity 的 onActivityResult 方法看到的是 65636
不要混用, 谢谢

**Comment by MarkMjw** [comment]
> 上面你的 forward 本就是普通跳转, 不是 startActivityForResult.
> 下面你的 forwardForResult 用对了. 但是你说 requestCode 对不上, 因为你不能混着用的. 你不能让我框架去接受, 你又自己去接受. 因为实现这个功能其实内部预埋了一个 Fragment 去 startActivityForResult 的, 所以你在你的 Activity 的 onActivityResult 方法看到的是 65636
> 不要混用, 谢谢

看wiki里面是这么写，我以为forward跳转然后在onActivityResult中取值这种最原始的方式是可行的。因为从ARouter切换过来，希望改动尽可能少。
![image](https://user-images.githubusercontent.com/4126838/78334790-f4d42000-75be-11ea-822b-59e42b8a3ef4.png)

**Comment by xiaojinzi123** [comment]
原先支持的. 是因为根绝 requestCode 有没有来判断是否是 startActivityForResult .
这个确实可以两者合而为一. 这样, 你现在用的是哪个版本的？我这边可以更新一个优化版本, 就优化这点

**Comment by MarkMjw** [comment]
> 原先支持的. 是因为根绝 requestCode 有没有来判断是否是 startActivityForResult .
> 这个确实可以两者合而为一. 这样, 你现在用的是哪个版本的？我这边可以更新一个优化版本, 就优化这点

最新的1.8.2.1-androidx，感谢。

**Comment by xiaojinzi123** [comment]
> > 原先支持的. 是因为根绝 requestCode 有没有来判断是否是 startActivityForResult .
> > 这个确实可以两者合而为一. 这样, 你现在用的是哪个版本的？我这边可以更新一个优化版本, 就优化这点
> 
> 最新的1.8.2.1-androidx，感谢。

已发布 1.8.2.2 优化版本. 感谢选择 `Component`
另外多建议尝试跳转拿 ActivityResult 和 使用页面拦截器、自定义 `Intent`、路由 Api 等高级功能.
真的会让你的代码变得更容易维护的

**Comment by MarkMjw** [comment]
> > > 原先支持的. 是因为根绝 requestCode 有没有来判断是否是 startActivityForResult .
> > > 这个确实可以两者合而为一. 这样, 你现在用的是哪个版本的？我这边可以更新一个优化版本, 就优化这点
> > 
> > 
> > 最新的1.8.2.1-androidx，感谢。
> 
> 已发布 1.8.2.2 优化版本. 感谢选择 `Component`
> 另外多建议尝试跳转拿 ActivityResult 和 使用页面拦截器、自定义 `Intent`、路由 Api 等高级功能.
> 真的会让你的代码变得更容易维护的

OK，主要是历史代码的原因，后面使用过程中会考虑这些方式，再次感谢。
