### ISSUE TITLE
fragment 跳转activity  传值问题

### ISSUE THREAD

**Issue by ganzhex2019** [xiaojinzi123/Component#58]
fragment的代码
Router
                    .with(this@HomeTabFragment)
                    .host("home")
                    .path("more")
                    .putString("classifyType", sectionList[i].classifyType)
                    .putInt("typeId", sectionList[i].typeId)
                    .forward()

activity的代码
 @JvmField
    @AttrValueAutowiredAnno("classifyType")
    var mClassifyType: String ?= null

    @JvmField
    @AttrValueAutowiredAnno("typeId")
    var mTypeId: Int ? = null

**Comment by ganzhex2019** [comment]
在activity中没有收到fragment传递过来的数据

**Comment by xiaojinzi123** [comment]
你先看下字段的引用有没有

![image](https://user-images.githubusercontent.com/12975743/78990054-faee7180-7b67-11ea-9e66-ed58de7ef2ef.png)

**Comment by ganzhex2019** [comment]
<img width="928" alt="屏幕快照 2020-04-10 下午8 21 00" src="https://user-images.githubusercontent.com/59903166/78990398-eeb6e400-7b68-11ea-8103-0a98da529005.png">
代码 生成了有  但是在activity中   对应的引用没有

**Comment by ganzhex2019** [comment]
页面是跳转过来了的  引用就是为空

**Comment by xiaojinzi123** [comment]
既然代码生成了, 说明生成的部分没有问题. 

那你可以调试一下代码. 看下 `Component.inject` 那句代码里面在哪一步出错了.
这样子即可排查出错误. 
请把调试出来的错误信息也粘贴一下

**Comment by ganzhex2019** [comment]
好的  我好像知道问题了   在文档里找到    Component.inject(this)  这句    看您的例子   找到了  谢谢

**Comment by xiaojinzi123** [comment]
....................................................................................................... 你没写这句吗？

**Comment by ganzhex2019** [comment]
是的  文档里没提    自己没注意  总觉得缺少点什么   于是仔细再看了你项目的代码

**Comment by xiaojinzi123** [comment]
你别骗我撒, [文档](https://github.com/xiaojinzi123/Component/wiki/%E5%B1%9E%E6%80%A7%E5%92%8C-Service-%E7%9A%84%E6%B3%A8%E5%85%A5) 中很明显有这么一段：

![image](https://user-images.githubusercontent.com/12975743/78991240-0e4f0c00-7b6b-11ea-94a3-65bb13395676.png)

这文档都很久没动了哦. 

反正问题解决就好了. 我这里关闭了撒.

**Comment by ganzhex2019** [comment]
谢谢 哥老关
