### ISSUE TITLE
路由拦截参数验证  

### ISSUE THREAD

**Issue by ganzhex2019** [xiaojinzi123/Component#59]
val rawContext = chain.request().rawOrTopActivity
        if (rawContext == null) {
            chain.callback().onError(Exception("context is null"))
            return
        }else{
            val request = chain.request()
            if (request.uri.getQueryParameter("typeId")!=null){
                chain.proceed(chain.request())
            }
        }

发现这里   没有我上面传递的typeId 这个字段  怎么在拦截器里对传递的参数进行验证呢  大佬

**Comment by xiaojinzi123** [comment]
大哥还是这个[文档](https://github.com/xiaojinzi123/Component/wiki/%E5%B1%9E%E6%80%A7%E5%92%8C-Service-%E7%9A%84%E6%B3%A8%E5%85%A5)啊 

手动获取的话, 如果要覆盖获取到 `Uri` 的 `query` 值, 那么你需要借助 `ParameterSupport` 工具类.
如果没有 `query` 的值要获取, 则拿到 `chain.request().bundle` 自己获取就行了. 

`ParameterSupport` 主要就是支持获取 原生 + Uri.query 的值, 你不借助工具类 `ParameterSupport` 是没办法获取到 `query` 的. 只能获取到原生的.

所以你上面获取参数, 就直接下面这样就行了
```
ParameterSupport.getInt(chain.request().bundle, "typeId")
```

**Comment by xiaojinzi123** [comment]
`Context` 只要你不用的话, 你就不要去验证 `Context` 是否为空的.  反正报任何错框架都会回调给你的. 
和你写 `chain.callback().onError(Exception("context is null"))` 没啥差别.

你肯定是看了我的 `Demo`, 我的 `Context` 是用到了. 所以需要验证, 避免空指针.

**Comment by ganzhex2019** [comment]
好的
