### ISSUE TITLE
我想在拦截器里面设置回调参数

### ISSUE THREAD

**Issue by guozhiqiang123** [xiaojinzi123/Component#61]
比如我在拦截器里面发起了一个网络请求，网络请求成功之后设置类似setResult(Activity.RESULT_OK,intent);这样的代码来响应startForResult这样启动。要实现这样的功能，我应该怎么写呢？

**Comment by guozhiqiang123** [comment]
我并不是真正的想要跳转到目标页面去，只是想在拦截器里面处理一些东西，然后就返回

**Comment by xiaojinzi123** [comment]
Component 并没有新设计整个跳转的过程. 路由模块的跳转其实和你原生跳转没什么区别.
填写参数-->生成 `request` --> 经过拦截器 --> 跳转 `Intent`. 跳转 `Intent` 分为 startActivity 和 startActivityForResult.
其实路由部分的功能就此结束, 这和你调用了 startActivity 和 startActivityForResult 就完成跳转是一样的. 
所以拦截器只是拦截器跳转这部分的. 你能在拦截器中直接回调的只能是成功与否. 拦截器不设计到 `setResult` 或者 返回 `ActivityResult` 等东西. 

而为什么有些回调可以拿到 `ActivityResult`, 是因为基础回调中, 又嵌套了一层回调. 在这层嵌套的回调中帮你处理了 onActivityResult, 并且回调给你. 

上面简单说了下路由的这些部分.

然后我看你的需求好像不需要使用跳转呀, 你就使用平常代码去获取数据不可以吗？
