### ISSUE TITLE
服务发现中怎么获取fragment 的实例呢 

### ISSUE THREAD

**Issue by ganzhex2019** [xiaojinzi123/Component#62]
例如 A模块中的 a fragment   在a中  有一个 viewpager   
B 模块中 b  fragment 有一个按钮 btn  点击 btn   需要a  fragment 的viewpager  切换  
在这我通过baseModule中创建一个switchService    A中实现这个Service

问题：  在ServiceImpl中 通过反射   或者 其他方式都不能 获取到 这个viewper
下面是我的代码 
a fragment ：
    fun switchFragment(position: Int): Boolean {
//        mainViewpager.currentItem = position
        mainViewpager.setCurrentItem(position, false)
        return true
    }
ServiceImpl：
@ServiceAnno(value = [SwitchNavService::class], singleTon = true)
class SwitchNavServiceImpl : SwitchNavService {

    init {
        toast("创建 服务")
    }

    override fun switch(index: Int) {
        LogUtils.error("切换$index")
      这里就是我实现的逻辑  拿不到viewpger实例  请问大哥指点一下   谢谢

    }

**Comment by xiaojinzi123** [comment]
你这种情况又不需要这样做的. 首先你这只是想在另外一个 Module 去控制 A Module 中的一个 ViewPager 的切换. 换而言之就是其他模块想控制 A Module 的一些视图.

像你那样创建接口和实现. 
实现 ServiceImpl 中你弄一个成员变量 int xxxPagerIndex; 不就完了

```
override fun switch(index: Int) {
         xxxPagerIndex = index;
}
// 下面你在提供一个监听方法不就完了, 让 A ViewPager 所在的界面创建之后来监听这个属性, 类似于点击事件的监听. 界面销毁了就反注册监听. 不就完了吗
```

**Comment by ganzhex2019** [comment]
是的 ，等下再试试你说的方法  谢谢啦   我就把issue关啦
在看你说的方法之前   我在上面的实现类中用了事件总线的方式处理，用事件总线的话  其实可以不用写服务接口的，但是为了模块化和调用起来方便，我还是觉得写服务接口有必要，对外部使用者不需要关注内部实现

**Comment by xiaojinzi123** [comment]
> 是的 ，等下再试试你说的方法 谢谢啦 我就把issue关啦
> 在看你说的方法之前 我在上面的实现类中用了事件总线的方式处理，用事件总线的话 其实可以不用写服务接口的，但是为了模块化和调用起来方便，我还是觉得写服务接口有必要，对外部使用者不需要关注内部实现

对的, 你理解的不错, 事件总线啥的其实你各个模块之间如果都用的话, 本就不合适, 对外提供的接口就应该清晰透明. 你模块内部使用一下还算可以吧. 

如果是我, 我会在项目中, 使用 RxJava 的热信号的. 不过你那样挺好的了, 可以的
