### ISSUE TITLE
在拦截器里跳转页面没有使用在them里全局设置的动画

### ISSUE THREAD

**Issue by InertiaOoo** [xiaojinzi123/Component#63]
像登陆的时候，被拦截进入登陆界面，登陆成功后回到拦截器再进行页面跳转时，这时的跳转动画用的是系统原生的而不是我在AndroidManifest的them里设置的动画，这是什么原因？
用这个方法跳转就会这样chain.proceed(chain.request());

**Comment by xiaojinzi123** [comment]
你这个问题看上去应该不是 `Component` 的问题.

你先确定下你自己用原生的代码启动的时候, 是否确定是你配置的动画.

**Comment by InertiaOoo** [comment]
好吧，是我在afterAction里加了finish才出现了这种情况，在基础Activity的onCreate,finish方法中加入动画后可以正常使用。

**Comment by xiaojinzi123** [comment]
> 好吧，是我在afterAction里加了finish才出现了这种情况，在基础Activity的onCreate,finish方法中加入动画后可以正常使用。

那现在就是没问题了吧. 还有的话再开启此 `issue` 即可. 我这里关闭了
