### ISSUE TITLE
使用Kotlin语法时候的问题

### ISSUE THREAD

**Issue by guozhiqiang123** [xiaojinzi123/Component#66]
最开始使用java书写Activity中代码,能够正常跳转，当把目标类转换成kotlin书写的时候，提示找不到目标Activity了。
```
@RouterAnno(hostAndPath = ActivityPath.MainActivity)
class MainActivity : BaseActivity() {
}
```
```
Router.with(this).hostAndPath(ActivityPath.MainActivity).forward();
```
提示的log:route fail：router://app/main/activity and errorClass is TargetActivityNotFoundException,errorMsg is 'router://app/main/activity'

**Comment by xiaojinzi123** [comment]
你是否由 java 模块的 annotationProcess 改成 kapt 呢.

**Comment by guozhiqiang123** [comment]
如果我是混编呢？该怎么依赖呢？annotationProcess 和kapt都依赖一遍吗

**Comment by xiaojinzi123** [comment]
> 如果我是混编呢？该怎么依赖呢？annotationProcess 和kapt都依赖一遍吗

依赖是一样的. 就是注解驱动器的使用是不同的。 

Java 模块是只要 Java 代码的模块, 没有配置 Kotlin, 你得用 annotationProcess
Kotlin 是指配置了 Kotlin 的模块, 即使你用 Java 写. 或者混着写. 你都得用 Kapt

**Comment by guozhiqiang123** [comment]
谢谢！我试试。
