### ISSUE TITLE
Gradle may disable incremental compilation as the following annotation processors are not incremental

### ISSUE THREAD

**Issue by dengsongnanx** [xiaojinzi123/Component#67]
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-component-compiler-1.8.2.2.jar (com.github.xiaojinzi123.Component:component-compiler:1.8.2.2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

**Comment by xiaojinzi123** [comment]
这并不是一个 bug, 是注解驱动器不支持增量编译. 这个目前影响你了吗?

**Comment by dengsongnanx** [comment]
项目编译失败 运行不了

**Comment by xiaojinzi123** [comment]
那不可能. 请仔细的再看一下依赖的文档. 是否没有按照文档的配置.

**Comment by xiaojinzi123** [comment]
或者你扫码进群. 方便沟通. 回头记得这里贴上原因

**Comment by xiaojinzi123** [comment]
配置的原因
