### ISSUE TITLE
作者是否能升级下java版本目前1.8编译提示低了

### ISSUE THREAD

**Issue by w290721955** [xiaojinzi123/Component#68]
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'

**Comment by xiaojinzi123** [comment]
升级不是不可以, 但是由于做组件化的很多都是比较老的项目. 所以有些时候我不得不考虑用更具有兼容性的版本. 
你这边应该仅仅是提示而已, 不会造成你运行有问题的吧. 
如果你这边真的需要, 我这边会考虑下. 但是我还是希望能覆盖的范围更广.

**Comment by w290721955** [comment]
理解，目前只是警告，主要这个警告编译时一个组件刷8次，看着有点不好看，可以考虑弄个支持的分支。

**Comment by xiaojinzi123** [comment]
后续我看看吧. 此 issue 也不关闭了, 后面处理了再来关闭这个 issue

**Comment by xiaojinzi123** [comment]
第一版的支持 java 8 的版本已经发布啦. 原先的信息后面尾加 -java8 就好了

**Comment by w290721955** [comment]
点赞！
