### ISSUE TITLE
ServiceManager.get方法死循环

### ISSUE THREAD

**Issue by pengbs** [xiaojinzi123/Component#69]
1.7.7.3-androidx版本，我看最新版本这个地方也没有调整。复现步骤：
1. 当在子线程调用ServiceManager.get(tClass)时，这个时候tClass也没有注册到map中，所以返回的就是null。
2. 在Utils.mainThreadCallable中tAtomicReference.set(callable.get())进去的就是null，也不会报异常。
3. 这时while (tAtomicReference.get() == null && exceptionAtomicReference.get() == null) {} 这个判断就会一直满足，就死循环卡死了

**Comment by xiaojinzi123** [comment]
感谢您这边提供的详细信息, 我这边复现一下, 如果存在今天就会发出更新包, 不用担心.

**Comment by xiaojinzi123** [comment]
兄弟, callable 的 get 方法都是生成的, 不会有返回 null 的时候, 你那里是自己往 ServiceManager 中 put 了一个 callable 吗？

**Comment by xiaojinzi123** [comment]
> 1.7.7.3-androidx版本，我看最新版本这个地方也没有调整。复现步骤：
> 
> 1. 当在子线程调用ServiceManager.get(tClass)时，这个时候tClass也没有注册到map中，所以返回的就是null。
> 2. 在Utils.mainThreadCallable中tAtomicReference.set(callable.get())进去的就是null，也不会报异常。
> 3. 这时while (tAtomicReference.get() == null && exceptionAtomicReference.get() == null) {} 这个判断就会一直满足，就死循环卡死了

此问题已解决, 确实是一个 Bug, 由于出现的条件是：子线程 + 没注册. 所以我们不太好测出来. 新版本已经解决此问题, 还望更新. 然后这个 bug 您这边发现是有一个奖励的. 可以加群. 我这边会给您相应的奖励.

**Comment by pengbs** [comment]
神速啊，已经申请加群了
