### ISSUE TITLE
kotlin Fragment 添加注解后,导致路由名已存在

### ISSUE THREAD

**Issue by wxmylife** [xiaojinzi123/Component#71]
业务Module 依赖:
```
kapt "com.github.xiaojinzi123.Component:component-compiler:1.8.2.3.1-androidx"
api project(path: ':base')
```

Base Module 依赖:
```
kapt "com.github.xiaojinzi123.Component:component-compiler:1.8.2.3.1-androidx"
api "com.github.xiaojinzi123.Component:component-impl:1.8.2.3.1-androidx"
```

Fragment 注解：
![1594781110684](https://user-images.githubusercontent.com/15435851/87497836-f961a780-c688-11ea-8a3b-a75cf98aedb6.jpg)

编译错误:
![1594781079178](https://user-images.githubusercontent.com/15435851/87497849-02eb0f80-c689-11ea-9d3d-1f8f4519882e.jpg)

**Comment by xiaojinzi123** [comment]
如提示所说, ”account_home“ 这个字符串你已经用过啦. 你查找一下

**Comment by xiaojinzi123** [comment]
另外, 1.8.2.3.1 是我为了排查一个问题临时发布的一个版本. 已经被删除, 请使用 1.8.2.3
这点非常抱歉, 我这边需要排查一个问题所致. 还望理解. 两者没有差别, 初始化您这边将 ComponentConfig 改为 Config 就好了

**Comment by wxmylife** [comment]
已采用1.8.2.3版本
全局搜索 account_home 并没有重复,如下图
![image](https://user-images.githubusercontent.com/15435851/87512989-8d903680-c6aa-11ea-9cf7-d5a9d8513f12.png)
全局查找 account_home 引用,如下图
![image](https://user-images.githubusercontent.com/15435851/87512822-4609aa80-c6aa-11ea-9071-0f08a596d5a9.png)

我现在有四个业务模块，均定义了 FragmentAnno(业务名_home) 的 四个不同 Fragment，报错也都是这四个 Fragment 名称都已存在，之前单模块使用 Activity , 并没有出现相同错误

问题还是
![image](https://user-images.githubusercontent.com/15435851/87513130-c92b0080-c6aa-11ea-9bbd-bfec65472985.png)

**Comment by xiaojinzi123** [comment]
加群, 我好帮你解决

**Comment by xiaojinzi123** [comment]
kotlin 中标记在方法上不能同时使用 @JvmStatic 注解. 感谢这位童鞋的反馈. 虽说不是一个问题. 但是也帮助我完善了文档. 谢谢
见文档 [https://github.com/xiaojinzi123/Component/wiki/%E8%B7%B3%E8%BD%AC-Fragment#%E6%A0%87%E8%AE%B0%E4%BD%A0%E7%9A%84-fragment](https://github.com/xiaojinzi123/Component/wiki/%E8%B7%B3%E8%BD%AC-Fragment#%E6%A0%87%E8%AE%B0%E4%BD%A0%E7%9A%84-fragment)
