### ISSUE TITLE
大佬  请教个问题

### ISSUE THREAD

**Issue by ganzhex2019** [xiaojinzi123/Component#72]
https://github.com/ganzhex2019/Component   这是我拷贝你的代码   修改为java8 androidx   避免在新项目的时候出现很多警告
但是在引用依赖包的时候出现  Failed to resolve: com.github.ganzhex2019.Component:component-impl:1.8.2.3   请问你之前出现过没

**Comment by ganzhex2019** [comment]
本地是引用ok 的  一般我们上传到 jitpack 后  引入方式是 com.github.用户名:项目名:版本号   但是我看你的是 com.github.用户名.项目名:archivesBaseName:版本号  ， 能指点下吗  谢谢啦

**Comment by xiaojinzi123** [comment]
抱歉, 刚刚在处理另一个问题. 刚看到. 
1. 首先你得确保你在 jitpack 上已经打包成功五个包. 这个你可以点击 jitpack 打包的日志滑动到最后去看.
2. 然后你要确保你的主 build.gradle 中已经有 jitpack 的仓库了. 如图:
![image](https://user-images.githubusercontent.com/12975743/87524570-e7006180-c6ba-11ea-8c69-60c4bfc58f47.png)
依赖失败的问题总结就是上面两点. 

另外, 真的不建议您这边亲自去弄. 虽说我有计划过度到 java8, 但是暂时没有时间. 
因为你可能要处理后续的每一个更新. 我建议您这边可以再等等我这边. 毕竟警告不是错误.

**Comment by ganzhex2019** [comment]
好的  谢谢啦   我就是想看看你这边的实现过程  了解了也就行了  再次谢谢您

**Comment by xiaojinzi123** [comment]
java8 的已经支持了, 建议尝试, 有问题及示反馈. 代码没改变, 主要是编译和target的 version 都升级到 8 啦

**Comment by ganzhex2019** [comment]
好的

xiaojinzi123 <notifications@github.com>于2020年7月16日 周四21:00写道：
