### ISSUE TITLE
该库支持Kotlin写的 Activity吗？我试了按照Java类的方式添加路由但是导航失败

### ISSUE THREAD

**Issue by jovanhuxiaowen** [xiaojinzi123/Component#73]
version： 1.8.2.2-androidx

**Comment by xiaojinzi123** [comment]
麻烦你信息贴全了. 错误信息和你 kotlin 的写法

**Comment by jovanhuxiaowen** [comment]
@RouterAnno(hostAndPath = RouterMap.NewsList.PATH)
class NewsListActivity : ObservableSourceActivity<UiEvent>(), Consumer<NewsListViewModel> {
....

**Comment by jovanhuxiaowen** [comment]
启动方法和java的Activity的写法一样
 Router.with(getContext()).hostAndPath(RouterMap.NewsList.PATH).forward();

**Comment by jovanhuxiaowen** [comment]
D/-------- Router --------: route fail：router://app/NewsList and errorClass is TargetActivityNotFoundException,errorMsg is 'router://app/NewsList'

**Comment by xiaojinzi123** [comment]
你自己注解驱动器改成 kapt 的方式了吗

**Comment by jovanhuxiaowen** [comment]
annotationProcessor "com.github.xiaojinzi123.Component:component-compiler:1.8.2.2-androidx"

项目是Java kotlin混写的

**Comment by xiaojinzi123** [comment]
哎, annotationProcessor 改成 kapt 啊. 提 issue 之前自己也要排查一下啊, issue 中都有步骤

**Comment by jovanhuxiaowen** [comment]
哦哦 感谢！
