### ISSUE TITLE
想问一个问题啊

### ISSUE THREAD

**Issue by nextmrwang** [xiaojinzi123/Component#74]
如果项目用到地图的地方很多，地图jar包集成在哪个模块？

**Comment by xiaojinzi123** [comment]
Component 仅仅致力于解决您在组件化中遇到的跨组件调用和路由的问题. 
这个问题你应该和你们团队进行讨论. 是作为一个基础的核心库使用. 
还是加一封装屏蔽在某一个业务组件中. 然后提供 Api 给其他模块用.
