### ISSUE TITLE
最新版使用withApi这种方式不能正常跳转

### ISSUE THREAD

**Issue by guozhiqiang123** [xiaojinzi123/Component#75]
如题。使用这种方式可以正常跳转。
```
 Router.with(this)
                    .hostAndPath(ActivityPath.MainActivity)
                    .forward();
```
使用这种方式就不行。
```
@HostAndPathAnno(ActivityPath.MainActivity)
    void skipMainActivity(
            Context context,
            @ParameterAnno("bottomTabPosition") int bottomTabPosition,
            @ParameterAnno("subTabPosition") int position,
            @ParameterAnno("isFromLoginOrRegister") boolean isFromLogin,
            @AfterActionAnno Action afterAction,
            Callback callback);
```
使用的版本是 1.8.3.2-androidx

确认业务模块已经加了注解器  annotationProcessor "com.github.xiaojinzi123.Component:component-compiler:1.8.3.2-androidx"

**Comment by guozhiqiang123** [comment]
![QQ截图20200806184100](https://user-images.githubusercontent.com/20378988/89522810-6560a700-d814-11ea-9f55-aee0e7cc6bf9.png)
并且我看了，文件是生成成功了的，但就是跳转不成功。

**Comment by guozhiqiang123** [comment]
![QQ截图20200806193030](https://user-images.githubusercontent.com/20378988/89527146-7234c900-d81b-11ea-8982-3735e2010b86.png)
![QQ截图20200806193052](https://user-images.githubusercontent.com/20378988/89527128-68ab6100-d81b-11ea-897e-38b1d3fedc4c.png)
![QQ截图20200806193052](https://user-images.githubusercontent.com/20378988/89527210-8b3d7a00-d81b-11ea-8e0f-52b9afd9bd95.png)
这就很尴尬了！明明我调用的是MainActivity,但是日志报的是找不到另外一个Activity。

**Comment by xiaojinzi123** [comment]
错误信息粘贴一下

**Comment by guozhiqiang123** [comment]
程序能正常运行起来，错误信息只有上面贴的那张图： route fail: router://0403...

**Comment by xiaojinzi123** [comment]
截图不完整, 后面的 errorClass is 我看不见了

**Comment by guozhiqiang123** [comment]
稍等，我切换一下分支给你贴上来

**Comment by xiaojinzi123** [comment]
你 Api 的形式调用跳转失败, 那么你拿着生成的那些代码去自己调用, 也是一样跳转失败的. 
跳转失败的原因肯定不是 withApi 的问题.
你看下你的跳转为什么失败信息是另一个路径, 你有写一些全局拦截器或者页面拦截器吗?
如果有, 你调试一下拦截器

**Comment by xiaojinzi123** [comment]
另外我怀疑, 某一个拦截器使用不慎, 造成了原有的跳转一直被你挂着. 你拦截器中又跳转了另一个. 你这个错误信息很可能是另一个跳转的信息.

**Comment by guozhiqiang123** [comment]
好的 我试试。

**Comment by guozhiqiang123** [comment]
果然是全局拦截器的问题，获取path的时候没有拼接host

**Comment by guozhiqiang123** [comment]
谢谢大佬！
