### ISSUE TITLE
我想问问大佬，host为何不能支持含有小数点的的字符串，例如:www.baidu.com 这样的host。

### ISSUE THREAD

**Issue by x930073498** [xiaojinzi123/Component#78]
如题！谢谢大佬提供这么好的库。

**Comment by xiaojinzi123** [comment]
你定义的 HOST 只是模块的名字, 同时也是路由表模块的 host, 这个 host 用在很多地方, 比如生成的类的名字的一部分. 所以不支持一些特殊的很正常.

然后你说能不能支持 www.baidu.com 这样的host 这样的 host, 其实是完全可以的. 
你的模块的 host 名称不支持, 不代表你的路由不可以支持. 你可以利用全局拦截器对原有配置的 host 进行扩展.

假设你的一个模块的 host 是 test, 你完全可以将 host = "www.baidu.com" 都替换成 test.
比如你写了一个拦截器, 拦截器中就几行代码, 对 Uri 的 host 进行判断, 如果是 "www.baidu.com", 则替换成 "test". 这样子可以让你的路由的功能大大增强. 这样子之后你的多个 host 其实都可以是指向到一个 host

又比如你写了一个全局拦截器, 如果判断到 scheme 是 "http" 或者 "https", 则修改整个路由的信息, 导向到一个通用的 Web 界面. 
这样你就可以在任何一个地方通过下面的方式, 直接路由到一个固定的 Web 页面. 代码范例看：[WebViewInterceptor](https://github.com/xiaojinzi123/Component/blob/develop/ModuleHelp/src/main/java/com/xiaojinzi/component/help/WebViewInterceptor.java)
```
Router.with(context).url("http://xxx/xxx").forward();
```

思想不滑坡, 办法总是有的. 而且上面的方法, 可以扩展的点很多. 基于全局拦截器你可以做的事情是很多的. 
比如日志监控, 全局修改, 根据后台下发的规则对修改路由 等等

**Comment by xiaojinzi123** [comment]
另外, 你觉得不错的话, 把 star 给我点了

**Comment by x930073498** [comment]
了解，谢谢大佬，star是肯定的。还有就是，大佬，貌似fragment的功能有点少的样子，不支持标准路由的样子。我的app是单activity模式，fragment较多，是否可以增强fragment获取的功能，与activity差不多的那种。

**Comment by xiaojinzi123** [comment]
> 了解，谢谢大佬，star是肯定的。还有就是，大佬，貌似fragment的功能有点少的样子，不支持标准路由的样子。我的app是单activity模式，fragment较多，是否可以增强fragment获取的功能，与activity差不多的那种。

那可能不太适合, 因为我们提供的跳转 Fragment 其实只是服务发现的方式获取到一个 Fragment, 而Fragment 在原生的使用上也不是跳转使用的, 而且 Fragment 不是交由系统跳转的, 我们没法去定义 Fragment 的跳转行为, 只能交给你自己处理. 所以在组件化上, 我是不建议使用单 Activity 的. 我们的项目, 也很多都是 Fragment, 但是最外层都会包一个 Activity. 
毕竟 Activity 才是真正实际意义上的一个跳转的目标.

**Comment by xiaojinzi123** [comment]
这个无论你用哪个框架都有这个问题. 那你不妨直接试一下 Google 官方的 Navigation, 看看满足你要求不

**Comment by x930073498** [comment]
嗯，了解，谢谢。我的app是早期的fragmentation加ARouter实现的，现在为了适应业务，ARouter都被我改得面目全非了。fragment的跳转被我用Activity的  Window.ID_ANDROID_CONTENT加载fragment代替了，当然这就和业务绑定了，和大佬设计的初衷有所冲突，所以可能只能自己慢慢弄了。

**Comment by x930073498** [comment]
navigation 我也看了，如果要用，对当前项目改动太大了。所以，只能慢慢往下摸索了。

**Comment by xiaojinzi123** [comment]
其实还有一个方式, 不知道你看下行不. 你的跳转都是 Fragment, 但是其实可以变成使用 Component 来跳转. 
Component 支持标记到静态的方法上, 只要方法是返回一个 Intent 的, 那么你的每一个跳转 Fragment 的行为, 都可以声明为一个静态方法, 比如下面的代码, 每一个跳转目标都是你项目中的唯一的 Activity, 只不过传递的参数不一样, 然后在 Activity 内部统一根据参数去获取 Fragment, 然后通过 Router.with("<传递过来的参数>").navigate() 获取到 Fragment 进行展示. 不过 Activity 的模式应该设置为 singleTop 的
```
public static Intent toXxxFragment(@NonNull RouterRequest request) {
        Intent intent = new Intent(request.getRawContext(), xxxActivity.class);
        // 指定开启系统相机的Action
        intent.putExtra("xxx", "xxxFragment")
        return intent;
    }
```

**Comment by xiaojinzi123** [comment]
整理了以下文档. 你可以看这个 [单Activity多Fragment](https://github.com/xiaojinzi123/Component/wiki/%E5%8D%95-Activity-%E5%A4%9A-Fragment)

**Comment by x930073498** [comment]
谢谢大佬，不错的方式，不过这就意味着要维护两套路由了。

**Comment by xiaojinzi123** [comment]
> 谢谢大佬，不错的方式，不过这就意味着要维护两套路由了。

ARouter 不支持那有啥办法. 哈哈. 不过替换工作很快的. 重复工作, 几个小时一个大的项目的都替换完了

**Comment by x930073498** [comment]
嗯，是的，还有一种思路，就是，寻思可不可以把DoActivityStartInterceptor 这个拦截器中做的事给开放出来，就是start这一步，如果这一步可以自定义，似乎也可以做到。

**Comment by xiaojinzi123** [comment]
不可以, 这个你放弃吧. 因为你没参与设计的工作. 其实开始的时候, Component 是支持静态的方法不返回 Intent 的. 也就是你刚刚说的做的事情放出来. 但是后面的实践证明, 一个可路由的目标必须需要是一个 intent. 如果放出来会打破原本框架的一些设计. 造成一些不可预计的问题. 所以后面就关掉了.
