### ISSUE TITLE
能否提供 ARouter 到 Component 的迁移指南？

### ISSUE THREAD

**Issue by LinXueyuanStdio** [xiaojinzi123/Component#80]
看了一下 wiki，没有相关到信息。

ARouter 的用法还是比较简单的，Components 如果对 ARouter 的每一种用法都提供了替代，那真是小母牛到南极--牛逼到了极点！

我打算转到 Components 了，希望提供一个相对完整到迁移文档。。。

**Comment by xiaojinzi123** [comment]
其实不用有文档的, 如果你用过 ARouter, 那么用 Component 应该上手会非常快. 而且上面你说的是如果. 事实就是 Component 的功能对于 ARouter 只多不少, 它的每一种用法都有实现. 并且还有它很多没有的功能. 
配置方面有 wiki 中的文档. 使用方面相信对于你用 ARouter 来说, 不是问题的啦. 
有任何问题可加群找群主问. 么的问题的哦

**Comment by LinXueyuanStdio** [comment]
你是站在已经掌握 Components 的角度来说的

问题是，我对 Components 不是很熟悉，如果要迁移，需要仔细找出每个迁移要注意的细节，这有很多坑

- 比如 Components 的模块有生命周期的概念，这在 ARouter 中是没有的，ARouter 一步加载所有能看见的模块。
- 比如 Components 的壳工程依赖了的模块数量变化后能不能自动加载模块？ARouter 中是自动加载所有模块的。
- 比如 Components 跳转时模块没加载的话能自动加载吗？ARouter 没有模块生命周期的概念，也不会有这个问题
- 比如 ARouter 的注解 AutoWired 一把梭，Components 有自己的不同的注解

以上都是一些小的坑，需要耗费很多精力

既然 Components 对标了 ARouter，就应该提供一个迁移指南，或者说功能对比、写法对比

这不是一句上手快能搪塞过去的

**Comment by LinXueyuanStdio** [comment]
我目前的项目有20+个模块，注解和跳转有几百处，散落在各个模块之中

没有一个完善的迁移指南，这工作量太大了

**Comment by xiaojinzi123** [comment]
行, 既然你认真的描述了一些场景, 那么我这边今晚下班之后, 迁移的文档会初稿会写出来. 但是可能不是特别完整. 但是会覆盖你基本所有的使用 ARouter 的场景和接入 Component 的注意点. 
感谢你选择 Component

**Comment by xiaojinzi123** [comment]
写了一个简单的 [迁移指南](https://github.com/xiaojinzi123/Component/wiki/ARouter-%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97). 
在这里也同时简明扼要的回答你上述的问题：
Component 支持自动注册和手动注册. 所以你的 1 和 2 两个问题也就没啥问题了. 如果你自动注册自然就无需管注册的事情. 手动注册的话, 在模块数量发生变化的时候, 你是需要理会的. 

你说 Component 跳转时如果模块没加载会加载吗. 你这个功能实际上是懒加载的一种体现. 但是其实这个功能在路由方面是不可能实现的. 因为有拦截器的存在, 你永远无法事先得知一个 Url 的目标 Activity 是在哪个模块的. 
而你可能看到有些框架说支持此功能, 我很负责任的告诉你, 都是假功能, 看着没问题实际上是有问题的. 
Component 不支持此种错误的功能的. 决定模块加载与否, 初始化的时候基本就决定了. 

最后一点注入相关的, 迁移指南中有讲到. 这里就不说了

**Comment by LinXueyuanStdio** [comment]
看了迁移指南，很完善，解决了我的问题

点赞 ohhhhhh!!!

**Comment by xiaojinzi123** [comment]
> 看了迁移指南，很完善，解决了我的问题
> 
> 点赞 ohhhhhh!!!

有问题再提, 我后面会完善那个迁移指南的
