### ISSUE TITLE
the host is not a valid name：module-developer

### ISSUE THREAD

**Issue by LinXueyuanStdio** [xiaojinzi123/Component#82]
host 里为什么不能有横杆
```
Caused by: java.lang.RuntimeException: the host is not a valid name：module-developer
	at com.xiaojinzi.component.BaseHostProcessor.init(BaseHostProcessor.java:30)
	at com.xiaojinzi.component.ModuleAppProcessor.init(ModuleAppProcessor.java:50)
```

**Comment by LinXueyuanStdio** [comment]
```
Caused by: com.xiaojinzi.component.ProcessException: the hostAndPath(/developer/RecordActivity) can't start with '/' and end with '/'
	at com.xiaojinzi.component.RouterProcessor.toRouterAnnoBean(RouterProcessor.java:140)
	at com.xiaojinzi.component.RouterProcessor.parseAnno(RouterProcessor.java:113)
	at com.xiaojinzi.component.RouterProcessor.process(RouterProcessor.java:87)
```

**Comment by LinXueyuanStdio** [comment]
健壮性太差了

**Comment by xiaojinzi123** [comment]
> 健壮性太差了

兄弟, 凡事都是有原因的. 你不问原因直接来一句 健壮性太差了?
模块的host名字最终和生成的 Class 名称有关系, 你觉得中间的 - 合理吗?
标准 Uri 的 host 开头是不允许有 "/" 的, path 必须 "/" 开头. host + Path 就必须开头不能是 "/", path 可以多段, 但是最后不能有 "/"
这些你了解吗? 
你直接整一句 健壮性太差了, 我实在是不明白啊老哥.

以后评论之前也请问问自己是否真的明白了再做结论. 另外框架有问题, 我一定会改的. 而不是这样的一句评论

**Comment by LinXueyuanStdio** [comment]
首先，框架根据这个host生成的 Class 我用得到吗？没有。那框架不会自己自动转化为一个合法的 Class 名称吗？而且这个host用来跳转的话加个“-”有什么不可以？
然后，“/”这个我理解。但先不管标准是什么，框架为什么不能自动将第一个识别为host？类似于linux目录路径的写法。这样更加友好。

我深入使用的时候发现Component自己定义的东西太多了，不简洁。各种场景需要用到不同的类，不像ARouter一样，只要提供ARouter、Autowired，内部自动处理所有情况。Component是Router.with()、ModuleManager、Component.inject()各种api，为什么不能Component.with()，Component.check()，Component.inject() 呢。虽然这样有利于开发者管理，但不利于使用者使用。

**Comment by xiaojinzi123** [comment]
Component 支持手动注册, ARouter 不支持(貌似新版支持了). 因为不是所有人都喜欢用 Gradle 插件的. 而且当模块下发的时候. 你是需要用到的
那么这时候你还认为 host 是用户用不到的吗? 假如用户发现需要加载的模块的名称加载不出模块的时候, 是不是该怪我了? 我能做对 host 转化的事情吗?

对于 ARouter 的使用, 设计不同, 使用当然不同. ARouter 的服务发现和路由是一起设计的, 而 Component 不是. 
并且 Component 的宗旨一直都是行为贴近系统, Api 分明 如果您这边觉得 Arouter 方便, 可以去使用 Arouter 哦.

**Comment by LinXueyuanStdio** [comment]
另外再提一个文档的问题。我不否认 Component 功能强大，但文档给我的感觉就是，罗列，零散，想到哪写到哪，有什么写什么，生怕没有把所有用法写出来。
这个你可以参考一下 ARouter 的文档

https://github.com/alibaba/ARouter/blob/master/README_CN.md

从基础用法123出发，再进阶123，再附加一些设计要点
比如

=======
### 六、其他
1. 路由中的分组概念

- SDK中针对所有的路径(/test/1 /test/2)进行分组，分组只有在分组中的某一个路径第一次被访问的时候，该分组才会被初始化
- 可以通过 @ Route 注解主动指定分组，否则使用路径中第一段字符串(/*/)作为分组
- 注意：一旦主动指定分组之后，应用内路由需要使用 ARouter.getInstance().build(path, group) 进行跳转，手动指定分组，否则无法找到
```
@Route(path = "/test/1", group = "app")
```
=======

这里group的作用是和host类似的，这里完全解释了group、path的含义。这一点 Component 一定能加以学习。

再看Component的文档，又多又散，相互引用。看wiki有十几篇，到处跳转。我理解，Component功能多确实文档多，但是就是过多了，希望能精简一下。

真的，你去看 ARouter 的文档，有条有理，就把 ARouter 这么一个复杂的框架的功能讲清楚了，你一定能学习到很多东西的。只有一页，不会花很多时间的。

如果看完你还不知道怎么改造现有文档，你可以从给标题加上123开始，也可以从合并基础功能相关的文档开始。

**Comment by LinXueyuanStdio** [comment]
我给 Component 怼这么多字不是说希望 Component 不好，而恰恰是希望 Component 更好，这一点你一定要知道。

上次从 ARouter 迁移到 Component 的文档把要点写出来了，不过写的不怎么完整，还有很大提升空间的。

**Comment by LinXueyuanStdio** [comment]
如果可以的话，给我编辑Wiki的权限，我自己来也是可以的

**Comment by LinXueyuanStdio** [comment]
回到host的问题，你说一些配置和声明的正确性是很必要的，我也认同。

但是host里加“-”这件事情，你仔细想一下，“-”不会影响到跳转路径的解析，这在使用时是合理的吧。

我们在 host 上的争执在于，“-”会影响到 Component 内部的处理，但不影响外部的使用。不过这个Class类名对使用者并不可见，可见的是 host 这个字符串。如果真的不能加“-”或者其他字符，请在文档里说明为什么不能这么写，为什么要这样设计。

**Comment by LinXueyuanStdio** [comment]
我刚刚又看了 issue，发现之前也有人说 host 为什么不支持 “www.baidu.com” 这样的字符串了。说明这是一个普遍的问题，要么是文档没有写清楚 host 的写法和用途，要么是这样设计有问题。

简单支持各种host的方法是，把非字母的字符都去掉，转化为全部小写紧凑的字符串作为新 host。这样设计后在文档里写清楚 host 的写法，才是最友好的
比如
```
www.baidu.com -> wwwbaiducom
baidu-com -> baiducom
baidu@com -> baiducom
BAIDU CoM -> baiducom
```

**Comment by xiaojinzi123** [comment]
> 我刚刚又看了 issue，发现之前也有人说 host 为什么不支持 “www.baidu.com” 这样的字符串了。说明这是一个普遍的问题，要么是文档没有写清楚 host 的写法和用途，要么是这样设计有问题。
> 
> 简单支持各种host的方法是，把非字母的字符都去掉，转化为全部小写紧凑的字符串作为新 host。这样设计后在文档里写清楚 host 的写法，才是最友好的
> 比如
> 
> ```
> www.baidu.com -> wwwbaiducom
> baidu-com -> baiducom
> baidu@com -> baiducom
> BAIDU CoM -> baiducom
> ```


> 如果可以的话，给我编辑Wiki的权限，我自己来也是可以的

ARouter 的迁移的文档编辑权限可以开放. 这个没啥问题.

**Comment by xiaojinzi123** [comment]
> 回到host的问题，你说一些配置和声明的正确性是很必要的，我也认同。
> 
> 但是host里加“-”这件事情，你仔细想一下，“-”不会影响到跳转路径的解析，这在使用时是合理的吧。
> 
> 我们在 host 上的争执在于，“-”会影响到 Component 内部的处理，但不影响外部的使用。不过这个Class类名对使用者并不可见，可见的是 host 这个字符串。如果真的不能加“-”或者其他字符，请在文档里说明为什么不能这么写，为什么要这样设计。

host 我一直强调不能转化的原因在于它牵扯到很多地方. 不过正如你说的. 按照道理我是可以实现它随意配置的. 
这个我回头弄个分支试试. 回头在反馈到这里. 目前如果想实现 host 是 "www.baidu.com" 这种, 只能写一个全局拦截器匹配到 "www.baidu.com" 进行替换. 这点确实不太好. 所以我有空试试, 时间不会太久. 我先保证我日常工作保质保量完成

**Comment by xiaojinzi123** [comment]
> 我给 Component 怼这么多字不是说希望 Component 不好，而恰恰是希望 Component 更好，这一点你一定要知道。
> 
> 上次从 ARouter 迁移到 Component 的文档把要点写出来了，不过写的不怎么完整，还有很大提升空间的。

文档这块呢, 一直都是有人反馈会更新一些. 确实有比较多的问题. 文档这块没的说, 确实应该有一个简单一点, 但是清楚的描述了核心功能以及注意点的文档. 

这点我一定出一个这样的文档. 记下了

**Comment by xiaojinzi123** [comment]
> > 我刚刚又看了 issue，发现之前也有人说 host 为什么不支持 “www.baidu.com” 这样的字符串了。说明这是一个普遍的问题，要么是文档没有写清楚 host 的写法和用途，要么是这样设计有问题。
> > 简单支持各种host的方法是，把非字母的字符都去掉，转化为全部小写紧凑的字符串作为新 host。这样设计后在文档里写清楚 host 的写法，才是最友好的
> > 比如
> > ```
> > www.baidu.com -> wwwbaiducom
> > baidu-com -> baiducom
> > baidu@com -> baiducom
> > BAIDU CoM -> baiducom
> > ```
> 
> > 如果可以的话，给我编辑Wiki的权限，我自己来也是可以的
> 
> ARouter 的迁移的文档编辑权限可以开放. 这个没啥问题.

权限不知道咋开. 知道的话教教我. 然后拉取 wiki 的方式应该也可以. 把 wiki 的 repo 拉取下去改完 pr 给我

**Comment by LinXueyuanStdio** [comment]
https://docs.github.com/cn/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by xiaojinzi123** [comment]
> https://docs.github.com/cn/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis

好了.

**Comment by xiaojinzi123** [comment]
新版 1.8.3.6 已经发布. 支持了 host 任意字符串.
