### ISSUE TITLE
ServiceManager.get()在非主线程容易引起死锁问题

### ISSUE THREAD

**Issue by lokier** [xiaojinzi123/Component#84]
suspend all histogram:	Sum: 171.764ms 99% C.I. 6us-485.520us Avg: 129.048us Max: 2085us
DALVIK THREADS (51):
"HeavyworkThread0" prio=10 tid=46 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x12d416f0 self=0xcecd8a00
  | sysTid=6346 nice=0 cgrp=default sched=0/0 handle=0xb5afc230
  | state=R schedstat=( 142224752045 781037013 20148 ) utm=14085 stm=137 core=7 HZ=100
  | stack=0xb59f9000-0xb59fb000 stackSize=1040KB
  | held mutexes= "mutator lock"(shared held)
  at com.xiaojinzi.component.support.Utils.mainThreadCallable(Utils.java:7)
  at com.xiaojinzi.component.impl.service.ServiceManager.get(ServiceManager.java:1)

ServiceManager.get()方法为什么要考虑线程环境，觉得没必要去考虑。或者提供另外一个新的不考虑线程环境的get()

**Comment by xiaojinzi123** [comment]
1. 升级到最新版本. 这种情况会有明显的报错. 会帮助你排查
2. ServiceManager.get() 最好不要实时去拿. 写成成员变量, 并初始化是最好的. 例如下面
class xxx {
      private Service1 service1 = ServiceManager.get(Service1.class)
      // ......
}

**Comment by xiaojinzi123** [comment]
至于为什么会有这种情况. 是因为, Component 会保证所有用户接触的地方调用线程都是主线程. 所以当子线程调用 get 的时候会卡住线程等待主线程. 如果这时候主线程等待这个线程. 就会死锁. 
如果改成你说的会和设计理念冲突. 目前暂时没有特别好的处理方式. 最好的方式就是让 get 方法在主线程上初始化, 放到成员变量上是最好的

**Comment by xiaojinzi123** [comment]
> suspend all histogram: Sum: 171.764ms 99% C.I. 6us-485.520us Avg: 129.048us Max: 2085us
> DALVIK THREADS (51):
> "HeavyworkThread0" prio=10 tid=46 Runnable
> | group="main" sCount=0 dsCount=0 flags=0 obj=0x12d416f0 self=0xcecd8a00
> | sysTid=6346 nice=0 cgrp=default sched=0/0 handle=0xb5afc230
> | state=R schedstat=( 142224752045 781037013 20148 ) utm=14085 stm=137 core=7 HZ=100
> | stack=0xb59f9000-0xb59fb000 stackSize=1040KB
> | held mutexes= "mutator lock"(shared held)
> at com.xiaojinzi.component.support.Utils.mainThreadCallable(Utils.java:7)
> at com.xiaojinzi.component.impl.service.ServiceManager.get(ServiceManager.java:1)
> 
> ServiceManager.get()方法为什么要考虑线程环境，觉得没必要去考虑。或者提供另外一个新的不考虑线程环境的get()

从 1.8.3.6 开始, 去除了 Fragment 和 服务发现的线程限制. 不会再出现这种问题了. 可以的话更新一下. 并且 Host 支持任意的字符串了
