### ISSUE TITLE
annotationProcessor  导致的模块加载失败报错

### ISSUE THREAD

**Issue by yetuweiba** [xiaojinzi123/Component#86]
目前是使用反射的形式来加载组件,debug的时候会报错:
模块 '****' 加载失败, 请根据链接中的内容自行排查! 

经过排查,发现编译的时候有报错:
'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.github.xiaojinzi123.Component:component-compiler:1.8.3.6-androidx'.

debug起来的时候报错: "模块名称"加载失败

在build.grade中将 annotationProcessor 改为使用kapt后重新编译运行后上述报错消失,但是我的模块里并没有kotlin的代码,这一点可能需要在文档上说一下,以便帮助排除错误

**Comment by xiaojinzi123** [comment]
首先感谢反馈问题. 

模块中没有 kotlin 代码, 不代表这个模块不是 kotlin 的. 只要你配置了 kotlin 相关的配置. 你就应该使用 kapt.
但是之前的 kotlin 的版本, 即使使用 annotationProcessor 也能处理 java 写的那些代码的. 我刚刚试了一下现在不行了
这个应该是 kotlin 的相关版本升级导致的. 

不过最重要的还是, 你只要配置了 kotlin 相关的配置, 就认为这个模块是一个 kotlin 的模块, kapt 它是兼容 java 代码的. 这点放心.

另外我会在配置的文档中特别提醒这点. 再次感谢你的反馈
