### ISSUE TITLE
给自己提一个 issue

### ISSUE THREAD

**Issue by xiaojinzi123** [xiaojinzi123/Component#88]
目前服务发现功能已经支持了多实现. 
但是有些时候有些实现不是全局的. 它可能只在某个界面存在的时候这个服务才有实现. 
那么服务发现的实现是否可以具备 scope 的功能, 当标记 @ActivityScope(XXX.class) 的时候. 如果这个 Activity 不存在, 则这个服务也没有不存在

欢迎看到的小伙伴来讨论

**Comment by LinXueyuanStdio** [comment]
服务的多实现怎么用？完善一下文档吧

如果有两个模块分别实现了同一个服务接口，我可以按路由标记来决定获得哪个模块里的实现类吗？

**Comment by xiaojinzi123** [comment]
> 服务的多实现怎么用？完善一下文档吧
> 
> 如果有两个模块分别实现了同一个服务接口，我可以按路由标记来决定获得哪个模块里的实现类吗？

@ServiceAnno(Xxx.class, name = "google play")
@ServiceAnno(Xxx.class, name = "huawei")

就是注解中加入了 name 字段, 默认是 ""
获取的时候 ServiceManager.get(Xxx.class, "gp") 即可

注入那边也支持了 name, 其实使用很简单, 最近忙的要死. 估计下周一开始能松一点然后补一下

**Comment by xiaojinzi123** [comment]
多实现的文档在 [这里](https://github.com/xiaojinzi123/Component/wiki/%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0%E7%9A%84%E5%A4%9A%E5%AE%9E%E7%8E%B0%E7%9A%84%E4%BD%BF%E7%94%A8)
