### ISSUE TITLE
AttrValueAutowiredAnno 无法注入  kotlin fragment

### ISSUE THREAD

**Issue by tongxurt** [xiaojinzi123/Component#91]
错误: relationType 在 UserListFragment 中是 private 访问控制
        target.relationType = ParameterSupport.getString(bundle,"relationType",target.relationType);
              
代码中 并没有设置private

@FragmentAnno(UserListFragment_Path)
public class UserListFragment : BaseListFragment<User>() {

    private val presenter = Presenter(this)

    @AttrValueAutowiredAnno("relationType")
    var relationType: String = ""
   ....

**Comment by xiaojinzi123** [comment]
注解驱动器没办法识别出 Kotlin 还是 Java. 
你可以添加 @JvmField 注解到字段.

**Comment by tongxurt** [comment]
解决了  感谢

> 注解驱动器没办法识别出 Kotlin 还是 Java.
> 你可以添加 @JvmField 注解到字段.

**Comment by tongxurt** [comment]
> 注解驱动器没办法识别出 Kotlin 还是 Java.
> 你可以添加 @JvmField 注解到字段.

大神， 我草率了

虽然上面报错没有了  但是并没有注入成功  我拿到的还是初始值 "aa", 是我缺了什么配置 或者代码吗

 const val UserListFragment_Path = "$Host.userListFragment"

@FragmentAnno(UserListFragment_Path)
public class UserListFragment : BaseListFragment<User>() {

    @JvmField
    @AttrValueAutowiredAnno("relationType")
    var relationType: String = "aa"

    private var keyword: String = ""
    private var followUserId: String = ""

   ....
}


跳转方法


RxRouter.with(UserListFragment_Path)
                .putString("relationType", relationType)
                .putString("keyword", keyword)
                .putString("followUserId", followUserId)
                .putSerializable("listParams", listParams)
                .navigate()

**Comment by xiaojinzi123** [comment]
你注入的代码执行了吗? 其实这个问题很好排查的. 你在你 Fragment 的 onCreateView 之类的方法中打一个断点. 然后看下 Fragment 上的 args 名称的 Bundle 里面有没有数据就好了. 如果有说明你的注入没成功. 你可以贴一下你是怎么注入的

**Comment by xiaojinzi123** [comment]
注解标记的属性只是告诉框架如何注入. 但是注入的那句代码还是要写的.  文档在[这里](https://github.com/xiaojinzi123/Component/wiki/%E5%B1%9E%E6%80%A7%E5%92%8C-Service-%E7%9A%84%E6%B3%A8%E5%85%A5)

**Comment by tongxurt** [comment]
> 注解标记的属性只是告诉框架如何注入. 但是注入的那句代码还是要写的. 文档在[这里](https://github.com/xiaojinzi123/Component/wiki/%E5%B1%9E%E6%80%A7%E5%92%8C-Service-%E7%9A%84%E6%B3%A8%E5%85%A5)

    @UiThread
    private static void inject(@NonNull Object target, @Nullable Bundle bundle,
                               boolean isAutoWireAttrValue,
                               boolean isAutoWireService) {
        Utils.checkMainThread();
        Utils.checkNullPointer(target, "target");
        String injectClassName = target.getClass().getName() + ComponentConstants.INJECT_SUFFIX;
        try {
            Class<?> targetInjectClass = Class.forName(injectClassName);
            Inject inject = (Inject) targetInjectClass.newInstance();
            if (isAutoWireService) {
                inject.injectService(target);
            }
            if (isAutoWireAttrValue) {
                if (bundle == null) {
                    inject.injectAttrValue(target);
                } else {
                    Utils.checkNullPointer(bundle, "bundle");
                    inject.injectAttrValue(target, bundle);
                }
            }
        } catch (Exception ignore) {
            LogUtil.log("class '" + target.getClass().getName() + "' inject fail");
        }

    }

这里会catch 异常  java.lang.ClassNotFoundException: xxx._inject  on path: DexPathList[[zip file  ... 尝试解决未果  请大神帮看看

**Comment by xiaojinzi123** [comment]
代码没生成这问题很明显是. 你应该跳转之类的也不能用呀.
