### ISSUE TITLE
SingleTask模式启动如何清除其栈顶所有的activity

### ISSUE THREAD

**Issue by lcyluo** [xiaojinzi123/Component#92]
如题，目前有这样一个场景，A(singleTask)->B->C->D；在D中要返回到A中，正常intent跳转，由于A为singleTask，所以BCD都会直接被移出栈。
这种场景下，Component该如何处理才能处理这种机制，实际项目中由于到达D的路径很多，所以复用系统的机制能最简单回到A界面；

**Comment by xiaojinzi123** [comment]
你就正常用不能达到你的目的吗？ 你就把 A 设置为 singleTask, 那你其他地方使用 Component 正常跳转不就完了.
Component 只是包装了跳转的方式和提供了跨组件的跳转. 并没有对实际的跳转做任何的改动.

**Comment by lcyluo** [comment]
我刚才已经发现这个问题了，由于我在调用路由后，再调用了D的finish，去掉D的finish()方法就可以实现这个功能了

**Comment by xiaojinzi123** [comment]
> 我刚才已经发现这个问题了，由于我在调用路由后，再调用了D的finish，去掉D的finish()方法就可以实现这个功能了

Component 的跳转回因为你 finish 关联的界面而取消的. 所以如果其他地方有 finish 的需求. 请在合适的地方调用. 比如回调中
有任何问题可以加群. 群里会有小伙伴解答你的问题

**Comment by lcyluo** [comment]
谢谢。我申请一下
