### ISSUE TITLE
v1.9.0-androidx-java8-Stable1 版本 编译生成代码有问题，生成的代码包含有已删除的override方法

### ISSUE THREAD

**Issue by Lianruoxia** [xiaojinzi123/Component#94]
![image](https://user-images.githubusercontent.com/12423171/120453388-958dbd80-c3c5-11eb-8069-bfa682175033.png)
![image](https://user-images.githubusercontent.com/12423171/120453415-9b839e80-c3c5-11eb-84c1-41c3b88eab04.png)

**Comment by xiaojinzi123** [comment]
你是升级了吧. 请升级所有的版本到 v1.9.0-androidx-java8-Stable1
而不是部分升级. 我自己项目一直都是保持最新的. 没发现问题哦. 而且这个是最新加的一个小功能哦
