### ISSUE TITLE
Feature request: Support KSP

### ISSUE THREAD

**Issue by MarkMjw** [xiaojinzi123/Component#96]
是否考虑下支持[KSP](https://github.com/google/ksp)呢？相比KAPT，KSP性能更好，对于Kotlin项目来说可以减少编译时间。

**Comment by xiaojinzi123** [comment]
> 是否考虑下支持[KSP](https://github.com/google/ksp)呢？相比KAPT，KSP性能更好，对于Kotlin项目来说可以减少编译时间。

有两个问题：
1. 是否放弃对 Java 的代码的支持了
2. 那些注解驱动器的代码应该全部要重写了吧

**Comment by MarkMjw** [comment]
> > 是否考虑下支持[KSP](https://github.com/google/ksp)呢？相比KAPT，KSP性能更好，对于Kotlin项目来说可以减少编译时间。
> 
> 有两个问题：
> 
> 1. 是否放弃对 Java 的代码的支持了
> 2. 那些注解驱动器的代码应该全部要重写了吧

第一个，按理说应该还是支持的，参考Jetpack room。
第二个，应该是要按照KSP的规则重写。

**Comment by xiaojinzi123** [comment]
> > > 是否考虑下支持[KSP](https://github.com/google/ksp)呢？相比KAPT，KSP性能更好，对于Kotlin项目来说可以减少编译时间。
> > 
> > 
> > 有两个问题：
> > 
> > 1. 是否放弃对 Java 的代码的支持了
> > 2. 那些注解驱动器的代码应该全部要重写了吧
> 
> 第一个，按理说应该还是支持的，参考Jetpack room。
> 第二个，应该是要按照KSP的规则重写。

如果能兼容 java 的话, 倒是可以慢慢的做迁移的. 我后续调研一下

**Comment by xiaojinzi123** [comment]
不过还有一个很重要的参考依据是：Google 官方的很多库, 都还使用 kapt 的方式. 我觉得他们的动向也是一个很重要的参考

**Comment by xiaojinzi123** [comment]
全面升级到 Kotlin, 不支持 Java 的版本已经发布了
仓库是：https://github.com/xiaojinzi123/KComponent
这个 issue 就关闭了
