### ISSUE TITLE
is your fragment or Activity is Destroyed 问题

### ISSUE THREAD

**Issue by zhangyuqi940503** [xiaojinzi123/Component#99]
在路由跳转之前 会判断context如果是activity，判断isFinishing() || isDestroyed()，如果返回true，就会抛这个异常。但是在项目中调用startactivity后调用finish，就会抛这个异常。这样不太合理吧？很多场景都是启动activitiy后就finish了上一个activity。这种情况是否有解决办法呢？
![image](https://user-images.githubusercontent.com/88325593/127860883-57ed2a3f-60e5-412d-a472-4782e308de43.png)
![image](https://user-images.githubusercontent.com/88325593/127860911-68afb97d-ddb1-421d-b32d-d51a0b0cf6ec.png)
![image](https://user-images.githubusercontent.com/88325593/127860944-2e350764-5cc8-4715-b4c0-52f1de0aa484.png)

**Comment by Zengyonghao** [comment]
确保跳转完成后进行finish  确保跳转完成可以在Callback的 onSuccess()回调中得到保证

**Comment by xiaojinzi123** [comment]
因为你用原生的 startActivity 和 finish 这两个方法. 最终发送消息到系统是顺序处理的. 所以不会有问题. 
但是你选择了一个路由库之后. 几乎都是异步的, 那么就没法保证这两个方法的先后顺序了. 
Component 呢为了避免出现, 界面销毁了, 但是可能路由任务还在走, 所以对任务和界面本身的生命周期是做了绑定的. 
你可以选择在回调中, 去销毁当前界面. 
另外你也可以针对本次的路由设置自动取消为 false 但是我是十分不建议这么做的!
